// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fp_sop,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7a100tcsg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.627125,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=277,HLS_SYN_LUT=3791,HLS_VERSION=2018_2}" *)

module fp_sop (
        ap_clk,
        ap_rst,
        kernel_patch_0_V,
        kernel_patch_1_V,
        kernel_patch_2_V,
        kernel_patch_3_V,
        kernel_patch_4_V,
        kernel_patch_5_V,
        kernel_patch_6_V,
        kernel_patch_7_V,
        kernel_patch_8_V,
        kernel_patch_9_V,
        kernel_patch_10_V,
        kernel_patch_11_V,
        kernel_patch_12_V,
        kernel_patch_13_V,
        kernel_patch_14_V,
        kernel_patch_15_V,
        kernel_patch_16_V,
        kernel_patch_17_V,
        kernel_patch_18_V,
        kernel_patch_19_V,
        kernel_patch_20_V,
        kernel_patch_21_V,
        kernel_patch_22_V,
        kernel_patch_23_V,
        kernel_patch_24_V,
        kernel_patch_25_V,
        kernel_patch_26_V,
        kernel_patch_27_V,
        kernel_patch_28_V,
        kernel_patch_29_V,
        kernel_patch_30_V,
        kernel_patch_31_V,
        kernel_patch_32_V,
        kernel_patch_33_V,
        kernel_patch_34_V,
        kernel_patch_35_V,
        kernel_patch_36_V,
        kernel_patch_37_V,
        kernel_patch_38_V,
        kernel_patch_39_V,
        kernel_patch_40_V,
        kernel_patch_41_V,
        kernel_patch_42_V,
        kernel_patch_43_V,
        kernel_patch_44_V,
        kernel_patch_45_V,
        kernel_patch_46_V,
        kernel_patch_47_V,
        kernel_patch_48_V,
        pixel_window_0_V,
        pixel_window_1_V,
        pixel_window_2_V,
        pixel_window_3_V,
        pixel_window_4_V,
        pixel_window_5_V,
        pixel_window_6_V,
        pixel_window_7_V,
        pixel_window_8_V,
        pixel_window_9_V,
        pixel_window_10_V,
        pixel_window_11_V,
        pixel_window_12_V,
        pixel_window_13_V,
        pixel_window_14_V,
        pixel_window_15_V,
        pixel_window_16_V,
        pixel_window_17_V,
        pixel_window_18_V,
        pixel_window_19_V,
        pixel_window_20_V,
        pixel_window_21_V,
        pixel_window_22_V,
        pixel_window_23_V,
        pixel_window_24_V,
        pixel_window_25_V,
        pixel_window_26_V,
        pixel_window_27_V,
        pixel_window_28_V,
        pixel_window_29_V,
        pixel_window_30_V,
        pixel_window_31_V,
        pixel_window_32_V,
        pixel_window_33_V,
        pixel_window_34_V,
        pixel_window_35_V,
        pixel_window_36_V,
        pixel_window_37_V,
        pixel_window_38_V,
        pixel_window_39_V,
        pixel_window_40_V,
        pixel_window_41_V,
        pixel_window_42_V,
        pixel_window_43_V,
        pixel_window_44_V,
        pixel_window_45_V,
        pixel_window_46_V,
        pixel_window_47_V,
        pixel_window_48_V,
        sop_enable,
        out_valid,
        out_valid_ap_vld,
        out_val_V,
        out_val_V_ap_vld
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input  [7:0] kernel_patch_0_V;
input  [7:0] kernel_patch_1_V;
input  [7:0] kernel_patch_2_V;
input  [7:0] kernel_patch_3_V;
input  [7:0] kernel_patch_4_V;
input  [7:0] kernel_patch_5_V;
input  [7:0] kernel_patch_6_V;
input  [7:0] kernel_patch_7_V;
input  [7:0] kernel_patch_8_V;
input  [7:0] kernel_patch_9_V;
input  [7:0] kernel_patch_10_V;
input  [7:0] kernel_patch_11_V;
input  [7:0] kernel_patch_12_V;
input  [7:0] kernel_patch_13_V;
input  [7:0] kernel_patch_14_V;
input  [7:0] kernel_patch_15_V;
input  [7:0] kernel_patch_16_V;
input  [7:0] kernel_patch_17_V;
input  [7:0] kernel_patch_18_V;
input  [7:0] kernel_patch_19_V;
input  [7:0] kernel_patch_20_V;
input  [7:0] kernel_patch_21_V;
input  [7:0] kernel_patch_22_V;
input  [7:0] kernel_patch_23_V;
input  [7:0] kernel_patch_24_V;
input  [7:0] kernel_patch_25_V;
input  [7:0] kernel_patch_26_V;
input  [7:0] kernel_patch_27_V;
input  [7:0] kernel_patch_28_V;
input  [7:0] kernel_patch_29_V;
input  [7:0] kernel_patch_30_V;
input  [7:0] kernel_patch_31_V;
input  [7:0] kernel_patch_32_V;
input  [7:0] kernel_patch_33_V;
input  [7:0] kernel_patch_34_V;
input  [7:0] kernel_patch_35_V;
input  [7:0] kernel_patch_36_V;
input  [7:0] kernel_patch_37_V;
input  [7:0] kernel_patch_38_V;
input  [7:0] kernel_patch_39_V;
input  [7:0] kernel_patch_40_V;
input  [7:0] kernel_patch_41_V;
input  [7:0] kernel_patch_42_V;
input  [7:0] kernel_patch_43_V;
input  [7:0] kernel_patch_44_V;
input  [7:0] kernel_patch_45_V;
input  [7:0] kernel_patch_46_V;
input  [7:0] kernel_patch_47_V;
input  [7:0] kernel_patch_48_V;
input  [7:0] pixel_window_0_V;
input  [7:0] pixel_window_1_V;
input  [7:0] pixel_window_2_V;
input  [7:0] pixel_window_3_V;
input  [7:0] pixel_window_4_V;
input  [7:0] pixel_window_5_V;
input  [7:0] pixel_window_6_V;
input  [7:0] pixel_window_7_V;
input  [7:0] pixel_window_8_V;
input  [7:0] pixel_window_9_V;
input  [7:0] pixel_window_10_V;
input  [7:0] pixel_window_11_V;
input  [7:0] pixel_window_12_V;
input  [7:0] pixel_window_13_V;
input  [7:0] pixel_window_14_V;
input  [7:0] pixel_window_15_V;
input  [7:0] pixel_window_16_V;
input  [7:0] pixel_window_17_V;
input  [7:0] pixel_window_18_V;
input  [7:0] pixel_window_19_V;
input  [7:0] pixel_window_20_V;
input  [7:0] pixel_window_21_V;
input  [7:0] pixel_window_22_V;
input  [7:0] pixel_window_23_V;
input  [7:0] pixel_window_24_V;
input  [7:0] pixel_window_25_V;
input  [7:0] pixel_window_26_V;
input  [7:0] pixel_window_27_V;
input  [7:0] pixel_window_28_V;
input  [7:0] pixel_window_29_V;
input  [7:0] pixel_window_30_V;
input  [7:0] pixel_window_31_V;
input  [7:0] pixel_window_32_V;
input  [7:0] pixel_window_33_V;
input  [7:0] pixel_window_34_V;
input  [7:0] pixel_window_35_V;
input  [7:0] pixel_window_36_V;
input  [7:0] pixel_window_37_V;
input  [7:0] pixel_window_38_V;
input  [7:0] pixel_window_39_V;
input  [7:0] pixel_window_40_V;
input  [7:0] pixel_window_41_V;
input  [7:0] pixel_window_42_V;
input  [7:0] pixel_window_43_V;
input  [7:0] pixel_window_44_V;
input  [7:0] pixel_window_45_V;
input  [7:0] pixel_window_46_V;
input  [7:0] pixel_window_47_V;
input  [7:0] pixel_window_48_V;
input   sop_enable;
output   out_valid;
output   out_valid_ap_vld;
output  [15:0] out_val_V;
output   out_val_V_ap_vld;

reg out_valid_ap_vld;
reg out_val_V_ap_vld;

wire   [0:0] sop_enable_read_read_fu_236_p2;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [12:0] tmp5_fu_2814_p2;
reg   [12:0] tmp5_reg_3679;
wire    ap_CS_fsm_state2;
wire   [12:0] tmp7_fu_2830_p2;
reg   [12:0] tmp7_reg_3684;
wire   [12:0] tmp10_fu_2846_p2;
reg   [12:0] tmp10_reg_3689;
wire   [12:0] tmp12_fu_2862_p2;
reg   [12:0] tmp12_reg_3694;
wire   [12:0] tmp16_fu_2878_p2;
reg   [12:0] tmp16_reg_3699;
wire   [12:0] tmp18_fu_2894_p2;
reg   [12:0] tmp18_reg_3704;
wire   [12:0] tmp21_fu_2910_p2;
reg   [12:0] tmp21_reg_3709;
wire   [12:0] tmp23_fu_2926_p2;
reg   [12:0] tmp23_reg_3714;
wire   [12:0] tmp28_fu_2942_p2;
reg   [12:0] tmp28_reg_3719;
wire   [12:0] tmp30_fu_2958_p2;
reg   [12:0] tmp30_reg_3724;
wire   [12:0] tmp33_fu_2974_p2;
reg   [12:0] tmp33_reg_3729;
wire   [12:0] tmp35_fu_2990_p2;
reg   [12:0] tmp35_reg_3734;
wire   [12:0] tmp39_fu_3006_p2;
reg   [12:0] tmp39_reg_3739;
wire   [12:0] tmp41_fu_3022_p2;
reg   [12:0] tmp41_reg_3744;
wire   [12:0] tmp44_fu_3038_p2;
reg   [12:0] tmp44_reg_3749;
wire   [12:0] tmp46_fu_3064_p2;
reg   [12:0] tmp46_reg_3754;
wire   [2:0] tmp52_fu_3102_p2;
reg   [2:0] tmp52_reg_3759;
wire   [2:0] tmp57_fu_3140_p2;
reg   [2:0] tmp57_reg_3764;
wire   [2:0] tmp63_fu_3178_p2;
reg   [2:0] tmp63_reg_3769;
wire   [2:0] tmp68_fu_3216_p2;
reg   [2:0] tmp68_reg_3774;
wire   [2:0] tmp75_fu_3254_p2;
reg   [2:0] tmp75_reg_3779;
wire   [2:0] tmp80_fu_3292_p2;
reg   [2:0] tmp80_reg_3784;
wire   [2:0] tmp86_fu_3330_p2;
reg   [2:0] tmp86_reg_3789;
wire   [1:0] tmp92_fu_3342_p2;
reg   [1:0] tmp92_reg_3794;
wire   [1:0] tmp93_fu_3348_p2;
reg   [1:0] tmp93_reg_3799;
wire   [1:0] tmp95_fu_3354_p2;
reg   [1:0] tmp95_reg_3804;
wire   [15:0] tmp2_fu_3444_p2;
reg   [15:0] tmp2_reg_3809;
wire    ap_CS_fsm_state3;
wire   [15:0] tmp25_fu_3534_p2;
reg   [15:0] tmp25_reg_3814;
wire   [5:0] tmp49_fu_3646_p2;
reg   [5:0] tmp49_reg_3819;
wire    ap_CS_fsm_state4;
wire   [7:0] p_Val2_s_fu_852_p0;
wire  signed [7:0] p_Val2_s_fu_852_p1;
wire   [15:0] p_Val2_s_fu_852_p2;
wire   [10:0] tmp_1_fu_858_p4;
wire   [0:0] tmp_49_fu_872_p3;
wire   [7:0] p_Val2_1_fu_892_p0;
wire  signed [7:0] p_Val2_1_fu_892_p1;
wire   [15:0] p_Val2_1_fu_892_p2;
wire   [10:0] tmp_4_fu_898_p4;
wire   [0:0] tmp_50_fu_912_p3;
wire   [7:0] p_Val2_2_fu_932_p0;
wire  signed [7:0] p_Val2_2_fu_932_p1;
wire   [15:0] p_Val2_2_fu_932_p2;
wire   [10:0] tmp_7_fu_938_p4;
wire   [0:0] tmp_51_fu_952_p3;
wire   [7:0] p_Val2_3_fu_972_p0;
wire  signed [7:0] p_Val2_3_fu_972_p1;
wire   [15:0] p_Val2_3_fu_972_p2;
wire   [10:0] tmp_s_fu_978_p4;
wire   [0:0] tmp_52_fu_992_p3;
wire   [7:0] p_Val2_4_fu_1012_p0;
wire  signed [7:0] p_Val2_4_fu_1012_p1;
wire   [15:0] p_Val2_4_fu_1012_p2;
wire   [10:0] tmp_5_fu_1018_p4;
wire   [0:0] tmp_53_fu_1032_p3;
wire   [7:0] p_Val2_5_fu_1052_p0;
wire  signed [7:0] p_Val2_5_fu_1052_p1;
wire   [15:0] p_Val2_5_fu_1052_p2;
wire   [10:0] tmp_2_fu_1058_p4;
wire   [0:0] tmp_54_fu_1072_p3;
wire   [7:0] p_Val2_6_fu_1092_p0;
wire  signed [7:0] p_Val2_6_fu_1092_p1;
wire   [15:0] p_Val2_6_fu_1092_p2;
wire   [10:0] tmp_3_fu_1098_p4;
wire   [0:0] tmp_55_fu_1112_p3;
wire   [7:0] p_Val2_7_fu_1132_p0;
wire  signed [7:0] p_Val2_7_fu_1132_p1;
wire   [15:0] p_Val2_7_fu_1132_p2;
wire   [10:0] tmp_6_fu_1138_p4;
wire   [0:0] tmp_56_fu_1152_p3;
wire   [7:0] p_Val2_8_fu_1172_p0;
wire  signed [7:0] p_Val2_8_fu_1172_p1;
wire   [15:0] p_Val2_8_fu_1172_p2;
wire   [10:0] tmp_8_fu_1178_p4;
wire   [0:0] tmp_57_fu_1192_p3;
wire   [7:0] p_Val2_9_fu_1212_p0;
wire  signed [7:0] p_Val2_9_fu_1212_p1;
wire   [15:0] p_Val2_9_fu_1212_p2;
wire   [10:0] tmp_9_fu_1218_p4;
wire   [0:0] tmp_58_fu_1232_p3;
wire   [7:0] p_Val2_10_fu_1252_p0;
wire  signed [7:0] p_Val2_10_fu_1252_p1;
wire   [15:0] p_Val2_10_fu_1252_p2;
wire   [10:0] tmp_10_fu_1258_p4;
wire   [0:0] tmp_59_fu_1272_p3;
wire   [7:0] p_Val2_11_fu_1292_p0;
wire  signed [7:0] p_Val2_11_fu_1292_p1;
wire   [15:0] p_Val2_11_fu_1292_p2;
wire   [10:0] tmp_11_fu_1298_p4;
wire   [0:0] tmp_60_fu_1312_p3;
wire   [7:0] p_Val2_12_fu_1332_p0;
wire  signed [7:0] p_Val2_12_fu_1332_p1;
wire   [15:0] p_Val2_12_fu_1332_p2;
wire   [10:0] tmp_12_fu_1338_p4;
wire   [0:0] tmp_61_fu_1352_p3;
wire   [7:0] p_Val2_13_fu_1372_p0;
wire  signed [7:0] p_Val2_13_fu_1372_p1;
wire   [15:0] p_Val2_13_fu_1372_p2;
wire   [10:0] tmp_13_fu_1378_p4;
wire   [0:0] tmp_62_fu_1392_p3;
wire   [7:0] p_Val2_14_fu_1412_p0;
wire  signed [7:0] p_Val2_14_fu_1412_p1;
wire   [15:0] p_Val2_14_fu_1412_p2;
wire   [10:0] tmp_14_fu_1418_p4;
wire   [0:0] tmp_63_fu_1432_p3;
wire   [7:0] p_Val2_15_fu_1452_p0;
wire  signed [7:0] p_Val2_15_fu_1452_p1;
wire   [15:0] p_Val2_15_fu_1452_p2;
wire   [10:0] tmp_15_fu_1458_p4;
wire   [0:0] tmp_64_fu_1472_p3;
wire   [7:0] p_Val2_16_fu_1492_p0;
wire  signed [7:0] p_Val2_16_fu_1492_p1;
wire   [15:0] p_Val2_16_fu_1492_p2;
wire   [10:0] tmp_16_fu_1498_p4;
wire   [0:0] tmp_65_fu_1512_p3;
wire   [7:0] p_Val2_17_fu_1532_p0;
wire  signed [7:0] p_Val2_17_fu_1532_p1;
wire   [15:0] p_Val2_17_fu_1532_p2;
wire   [10:0] tmp_17_fu_1538_p4;
wire   [0:0] tmp_66_fu_1552_p3;
wire   [7:0] p_Val2_18_fu_1572_p0;
wire  signed [7:0] p_Val2_18_fu_1572_p1;
wire   [15:0] p_Val2_18_fu_1572_p2;
wire   [10:0] tmp_18_fu_1578_p4;
wire   [0:0] tmp_67_fu_1592_p3;
wire   [7:0] p_Val2_19_fu_1612_p0;
wire  signed [7:0] p_Val2_19_fu_1612_p1;
wire   [15:0] p_Val2_19_fu_1612_p2;
wire   [10:0] tmp_19_fu_1618_p4;
wire   [0:0] tmp_68_fu_1632_p3;
wire   [7:0] p_Val2_20_fu_1652_p0;
wire  signed [7:0] p_Val2_20_fu_1652_p1;
wire   [15:0] p_Val2_20_fu_1652_p2;
wire   [10:0] tmp_20_fu_1658_p4;
wire   [0:0] tmp_69_fu_1672_p3;
wire   [7:0] p_Val2_21_fu_1692_p0;
wire  signed [7:0] p_Val2_21_fu_1692_p1;
wire   [15:0] p_Val2_21_fu_1692_p2;
wire   [10:0] tmp_21_fu_1698_p4;
wire   [0:0] tmp_70_fu_1712_p3;
wire   [7:0] p_Val2_22_fu_1732_p0;
wire  signed [7:0] p_Val2_22_fu_1732_p1;
wire   [15:0] p_Val2_22_fu_1732_p2;
wire   [10:0] tmp_22_fu_1738_p4;
wire   [0:0] tmp_71_fu_1752_p3;
wire   [7:0] p_Val2_23_fu_1772_p0;
wire  signed [7:0] p_Val2_23_fu_1772_p1;
wire   [15:0] p_Val2_23_fu_1772_p2;
wire   [10:0] tmp_23_fu_1778_p4;
wire   [0:0] tmp_72_fu_1792_p3;
wire   [7:0] p_Val2_24_fu_1812_p0;
wire  signed [7:0] p_Val2_24_fu_1812_p1;
wire   [15:0] p_Val2_24_fu_1812_p2;
wire   [10:0] tmp_24_fu_1818_p4;
wire   [0:0] tmp_73_fu_1832_p3;
wire   [7:0] p_Val2_25_fu_1852_p0;
wire  signed [7:0] p_Val2_25_fu_1852_p1;
wire   [15:0] p_Val2_25_fu_1852_p2;
wire   [10:0] tmp_25_fu_1858_p4;
wire   [0:0] tmp_74_fu_1872_p3;
wire   [7:0] p_Val2_26_fu_1892_p0;
wire  signed [7:0] p_Val2_26_fu_1892_p1;
wire   [15:0] p_Val2_26_fu_1892_p2;
wire   [10:0] tmp_26_fu_1898_p4;
wire   [0:0] tmp_75_fu_1912_p3;
wire   [7:0] p_Val2_27_fu_1932_p0;
wire  signed [7:0] p_Val2_27_fu_1932_p1;
wire   [15:0] p_Val2_27_fu_1932_p2;
wire   [10:0] tmp_27_fu_1938_p4;
wire   [0:0] tmp_76_fu_1952_p3;
wire   [7:0] p_Val2_28_fu_1972_p0;
wire  signed [7:0] p_Val2_28_fu_1972_p1;
wire   [15:0] p_Val2_28_fu_1972_p2;
wire   [10:0] tmp_28_fu_1978_p4;
wire   [0:0] tmp_77_fu_1992_p3;
wire   [7:0] p_Val2_29_fu_2012_p0;
wire  signed [7:0] p_Val2_29_fu_2012_p1;
wire   [15:0] p_Val2_29_fu_2012_p2;
wire   [10:0] tmp_29_fu_2018_p4;
wire   [0:0] tmp_78_fu_2032_p3;
wire   [7:0] p_Val2_30_fu_2052_p0;
wire  signed [7:0] p_Val2_30_fu_2052_p1;
wire   [15:0] p_Val2_30_fu_2052_p2;
wire   [10:0] tmp_30_fu_2058_p4;
wire   [0:0] tmp_79_fu_2072_p3;
wire   [7:0] p_Val2_31_fu_2092_p0;
wire  signed [7:0] p_Val2_31_fu_2092_p1;
wire   [15:0] p_Val2_31_fu_2092_p2;
wire   [10:0] tmp_31_fu_2098_p4;
wire   [0:0] tmp_80_fu_2112_p3;
wire   [7:0] p_Val2_32_fu_2132_p0;
wire  signed [7:0] p_Val2_32_fu_2132_p1;
wire   [15:0] p_Val2_32_fu_2132_p2;
wire   [10:0] tmp_32_fu_2138_p4;
wire   [0:0] tmp_81_fu_2152_p3;
wire   [7:0] p_Val2_33_fu_2172_p0;
wire  signed [7:0] p_Val2_33_fu_2172_p1;
wire   [15:0] p_Val2_33_fu_2172_p2;
wire   [10:0] tmp_33_fu_2178_p4;
wire   [0:0] tmp_82_fu_2192_p3;
wire   [7:0] p_Val2_34_fu_2212_p0;
wire  signed [7:0] p_Val2_34_fu_2212_p1;
wire   [15:0] p_Val2_34_fu_2212_p2;
wire   [10:0] tmp_34_fu_2218_p4;
wire   [0:0] tmp_83_fu_2232_p3;
wire   [7:0] p_Val2_35_fu_2252_p0;
wire  signed [7:0] p_Val2_35_fu_2252_p1;
wire   [15:0] p_Val2_35_fu_2252_p2;
wire   [10:0] tmp_35_fu_2258_p4;
wire   [0:0] tmp_84_fu_2272_p3;
wire   [7:0] p_Val2_36_fu_2292_p0;
wire  signed [7:0] p_Val2_36_fu_2292_p1;
wire   [15:0] p_Val2_36_fu_2292_p2;
wire   [10:0] tmp_36_fu_2298_p4;
wire   [0:0] tmp_85_fu_2312_p3;
wire   [7:0] p_Val2_37_fu_2332_p0;
wire  signed [7:0] p_Val2_37_fu_2332_p1;
wire   [15:0] p_Val2_37_fu_2332_p2;
wire   [10:0] tmp_37_fu_2338_p4;
wire   [0:0] tmp_86_fu_2352_p3;
wire   [7:0] p_Val2_38_fu_2372_p0;
wire  signed [7:0] p_Val2_38_fu_2372_p1;
wire   [15:0] p_Val2_38_fu_2372_p2;
wire   [10:0] tmp_38_fu_2378_p4;
wire   [0:0] tmp_87_fu_2392_p3;
wire   [7:0] p_Val2_39_fu_2412_p0;
wire  signed [7:0] p_Val2_39_fu_2412_p1;
wire   [15:0] p_Val2_39_fu_2412_p2;
wire   [10:0] tmp_39_fu_2418_p4;
wire   [0:0] tmp_88_fu_2432_p3;
wire   [7:0] p_Val2_40_fu_2452_p0;
wire  signed [7:0] p_Val2_40_fu_2452_p1;
wire   [15:0] p_Val2_40_fu_2452_p2;
wire   [10:0] tmp_40_fu_2458_p4;
wire   [0:0] tmp_89_fu_2472_p3;
wire   [7:0] p_Val2_41_fu_2492_p0;
wire  signed [7:0] p_Val2_41_fu_2492_p1;
wire   [15:0] p_Val2_41_fu_2492_p2;
wire   [10:0] tmp_41_fu_2498_p4;
wire   [0:0] tmp_90_fu_2512_p3;
wire   [7:0] p_Val2_42_fu_2532_p0;
wire  signed [7:0] p_Val2_42_fu_2532_p1;
wire   [15:0] p_Val2_42_fu_2532_p2;
wire   [10:0] tmp_42_fu_2538_p4;
wire   [0:0] tmp_91_fu_2552_p3;
wire   [7:0] p_Val2_43_fu_2572_p0;
wire  signed [7:0] p_Val2_43_fu_2572_p1;
wire   [15:0] p_Val2_43_fu_2572_p2;
wire   [10:0] tmp_43_fu_2578_p4;
wire   [0:0] tmp_92_fu_2592_p3;
wire   [7:0] p_Val2_44_fu_2612_p0;
wire  signed [7:0] p_Val2_44_fu_2612_p1;
wire   [15:0] p_Val2_44_fu_2612_p2;
wire   [10:0] tmp_44_fu_2618_p4;
wire   [0:0] tmp_93_fu_2632_p3;
wire   [7:0] p_Val2_45_fu_2652_p0;
wire  signed [7:0] p_Val2_45_fu_2652_p1;
wire   [15:0] p_Val2_45_fu_2652_p2;
wire   [10:0] tmp_45_fu_2658_p4;
wire   [0:0] tmp_94_fu_2672_p3;
wire   [7:0] p_Val2_46_fu_2692_p0;
wire  signed [7:0] p_Val2_46_fu_2692_p1;
wire   [15:0] p_Val2_46_fu_2692_p2;
wire   [10:0] tmp_46_fu_2698_p4;
wire   [0:0] tmp_95_fu_2712_p3;
wire   [7:0] p_Val2_47_fu_2732_p0;
wire  signed [7:0] p_Val2_47_fu_2732_p1;
wire   [15:0] p_Val2_47_fu_2732_p2;
wire   [10:0] tmp_47_fu_2738_p4;
wire   [0:0] tmp_96_fu_2752_p3;
wire   [7:0] p_Val2_48_fu_2772_p0;
wire  signed [7:0] p_Val2_48_fu_2772_p1;
wire   [15:0] p_Val2_48_fu_2772_p2;
wire   [10:0] tmp_48_fu_2778_p4;
wire   [0:0] tmp_97_fu_2792_p3;
wire  signed [11:0] p_Val2_4_cast_fu_908_p1;
wire  signed [11:0] p_Val2_7_cast_fu_948_p1;
wire   [11:0] tmp6_fu_2804_p2;
wire  signed [12:0] tmp6_cast_fu_2810_p1;
wire  signed [12:0] p_Val2_1_cast_fu_868_p1;
wire  signed [11:0] p_Val2_13_cast_fu_1028_p1;
wire  signed [11:0] p_Val2_16_cast_fu_1068_p1;
wire   [11:0] tmp8_fu_2820_p2;
wire  signed [12:0] tmp8_cast_fu_2826_p1;
wire  signed [12:0] p_Val2_10_cast_fu_988_p1;
wire  signed [11:0] p_Val2_25_cast_fu_1188_p1;
wire  signed [11:0] p_Val2_28_cast_fu_1228_p1;
wire   [11:0] tmp_fu_2836_p2;
wire  signed [12:0] tmp11_cast_fu_2842_p1;
wire  signed [12:0] p_Val2_22_cast_fu_1148_p1;
wire  signed [11:0] p_Val2_34_cast_fu_1308_p1;
wire  signed [11:0] p_Val2_37_cast_fu_1348_p1;
wire   [11:0] tmp11_fu_2852_p2;
wire  signed [12:0] tmp13_cast_fu_2858_p1;
wire  signed [12:0] p_Val2_31_cast_fu_1268_p1;
wire  signed [11:0] p_Val2_43_cast_fu_1428_p1;
wire  signed [11:0] p_Val2_46_cast_fu_1468_p1;
wire   [11:0] tmp13_fu_2868_p2;
wire  signed [12:0] tmp17_cast_fu_2874_p1;
wire  signed [12:0] p_Val2_40_cast_fu_1388_p1;
wire  signed [11:0] p_Val2_52_cast_fu_1548_p1;
wire  signed [11:0] p_Val2_55_cast_fu_1588_p1;
wire   [11:0] tmp17_fu_2884_p2;
wire  signed [12:0] tmp19_cast_fu_2890_p1;
wire  signed [12:0] p_Val2_49_cast_fu_1508_p1;
wire  signed [11:0] p_Val2_61_cast_fu_1668_p1;
wire  signed [11:0] p_Val2_64_cast_fu_1708_p1;
wire   [11:0] tmp19_fu_2900_p2;
wire  signed [12:0] tmp22_cast_fu_2906_p1;
wire  signed [12:0] p_Val2_58_cast_fu_1628_p1;
wire  signed [11:0] p_Val2_70_cast_fu_1788_p1;
wire  signed [11:0] p_Val2_73_cast_fu_1828_p1;
wire   [11:0] tmp22_fu_2916_p2;
wire  signed [12:0] tmp24_cast_fu_2922_p1;
wire  signed [12:0] p_Val2_67_cast_fu_1748_p1;
wire  signed [11:0] p_Val2_79_cast_fu_1908_p1;
wire  signed [11:0] p_Val2_82_cast_fu_1948_p1;
wire   [11:0] tmp24_fu_2932_p2;
wire  signed [12:0] tmp29_cast_fu_2938_p1;
wire  signed [12:0] p_Val2_76_cast_fu_1868_p1;
wire  signed [11:0] p_Val2_88_cast_fu_2028_p1;
wire  signed [11:0] p_Val2_91_cast_fu_2068_p1;
wire   [11:0] tmp29_fu_2948_p2;
wire  signed [12:0] tmp31_cast_fu_2954_p1;
wire  signed [12:0] p_Val2_85_cast_fu_1988_p1;
wire  signed [11:0] p_Val2_97_cast_fu_2148_p1;
wire  signed [11:0] p_Val2_100_cast_fu_2188_p1;
wire   [11:0] tmp31_fu_2964_p2;
wire  signed [12:0] tmp34_cast_fu_2970_p1;
wire  signed [12:0] p_Val2_94_cast_fu_2108_p1;
wire  signed [11:0] p_Val2_106_cast_fu_2268_p1;
wire  signed [11:0] p_Val2_109_cast_fu_2308_p1;
wire   [11:0] tmp34_fu_2980_p2;
wire  signed [12:0] tmp36_cast_fu_2986_p1;
wire  signed [12:0] p_Val2_103_cast_fu_2228_p1;
wire  signed [11:0] p_Val2_115_cast_fu_2388_p1;
wire  signed [11:0] p_Val2_118_cast_fu_2428_p1;
wire   [11:0] tmp36_fu_2996_p2;
wire  signed [12:0] tmp40_cast_fu_3002_p1;
wire  signed [12:0] p_Val2_112_cast_fu_2348_p1;
wire  signed [11:0] p_Val2_124_cast_fu_2508_p1;
wire  signed [11:0] p_Val2_127_cast_fu_2548_p1;
wire   [11:0] tmp40_fu_3012_p2;
wire  signed [12:0] tmp42_cast_fu_3018_p1;
wire  signed [12:0] p_Val2_121_cast_fu_2468_p1;
wire  signed [11:0] p_Val2_133_cast_fu_2628_p1;
wire  signed [11:0] p_Val2_136_cast_fu_2668_p1;
wire   [11:0] tmp42_fu_3028_p2;
wire  signed [12:0] tmp45_cast_fu_3034_p1;
wire  signed [12:0] p_Val2_130_cast_fu_2588_p1;
wire  signed [11:0] p_Val2_139_cast_fu_2708_p1;
wire  signed [11:0] p_Val2_142_cast_fu_2748_p1;
wire   [11:0] tmp45_fu_3044_p2;
wire  signed [11:0] p_Val2_145_cast_fu_2788_p1;
wire  signed [11:0] p_Val2_19_cast_fu_1108_p1;
wire   [11:0] tmp47_fu_3054_p2;
wire  signed [12:0] tmp48_cast_fu_3060_p1;
wire  signed [12:0] tmp47_cast_fu_3050_p1;
wire   [1:0] p_Result_1_cast_fu_880_p1;
wire   [1:0] p_Result_3_cast_fu_920_p1;
wire   [1:0] tmp48_fu_3070_p2;
wire   [1:0] p_Result_12_cast_fu_1120_p1;
wire   [1:0] tmp53_fu_3076_p2;
wire   [1:0] p_Result_7_cast_fu_1000_p1;
wire   [1:0] p_Result_9_cast_fu_1040_p1;
wire   [1:0] tmp54_fu_3086_p2;
wire   [1:0] p_Result_5_cast_fu_960_p1;
wire   [1:0] tmp55_fu_3092_p2;
wire   [2:0] tmp55_cast_fu_3098_p1;
wire   [2:0] tmp53_cast_fu_3082_p1;
wire   [1:0] p_Result_14_cast_fu_1160_p1;
wire   [1:0] p_Result_16_cast_fu_1200_p1;
wire   [1:0] tmp56_fu_3108_p2;
wire   [1:0] p_Result_10_cast_fu_1080_p1;
wire   [1:0] tmp58_fu_3114_p2;
wire   [1:0] p_Result_20_cast_fu_1280_p1;
wire   [1:0] p_Result_22_cast_fu_1320_p1;
wire   [1:0] tmp59_fu_3124_p2;
wire   [1:0] p_Result_18_cast_fu_1240_p1;
wire   [1:0] tmp60_fu_3130_p2;
wire   [2:0] tmp60_cast_fu_3136_p1;
wire   [2:0] tmp58_cast_fu_3120_p1;
wire   [1:0] p_Result_26_cast_fu_1400_p1;
wire   [1:0] p_Result_28_cast_fu_1440_p1;
wire   [1:0] tmp61_fu_3146_p2;
wire   [1:0] p_Result_24_cast_fu_1360_p1;
wire   [1:0] tmp64_fu_3152_p2;
wire   [1:0] p_Result_32_cast_fu_1520_p1;
wire   [1:0] p_Result_34_cast_fu_1560_p1;
wire   [1:0] tmp65_fu_3162_p2;
wire   [1:0] p_Result_30_cast_fu_1480_p1;
wire   [1:0] tmp66_fu_3168_p2;
wire   [2:0] tmp66_cast_fu_3174_p1;
wire   [2:0] tmp64_cast_fu_3158_p1;
wire   [1:0] p_Result_38_cast_fu_1640_p1;
wire   [1:0] p_Result_40_cast_fu_1680_p1;
wire   [1:0] tmp67_fu_3184_p2;
wire   [1:0] p_Result_36_cast_fu_1600_p1;
wire   [1:0] tmp69_fu_3190_p2;
wire   [1:0] p_Result_44_cast_fu_1760_p1;
wire   [1:0] p_Result_46_cast_fu_1800_p1;
wire   [1:0] tmp70_fu_3200_p2;
wire   [1:0] p_Result_42_cast_fu_1720_p1;
wire   [1:0] tmp71_fu_3206_p2;
wire   [2:0] tmp71_cast_fu_3212_p1;
wire   [2:0] tmp69_cast_fu_3196_p1;
wire   [1:0] p_Result_50_cast_fu_1880_p1;
wire   [1:0] p_Result_52_cast_fu_1920_p1;
wire   [1:0] tmp72_fu_3222_p2;
wire   [1:0] p_Result_48_cast_fu_1840_p1;
wire   [1:0] tmp76_fu_3228_p2;
wire   [1:0] p_Result_56_cast_fu_2000_p1;
wire   [1:0] p_Result_58_cast_fu_2040_p1;
wire   [1:0] tmp77_fu_3238_p2;
wire   [1:0] p_Result_54_cast_fu_1960_p1;
wire   [1:0] tmp78_fu_3244_p2;
wire   [2:0] tmp78_cast_fu_3250_p1;
wire   [2:0] tmp76_cast_fu_3234_p1;
wire   [1:0] p_Result_62_cast_fu_2120_p1;
wire   [1:0] p_Result_64_cast_fu_2160_p1;
wire   [1:0] tmp79_fu_3260_p2;
wire   [1:0] p_Result_60_cast_fu_2080_p1;
wire   [1:0] tmp81_fu_3266_p2;
wire   [1:0] p_Result_68_cast_fu_2240_p1;
wire   [1:0] p_Result_70_cast_fu_2280_p1;
wire   [1:0] tmp82_fu_3276_p2;
wire   [1:0] p_Result_66_cast_fu_2200_p1;
wire   [1:0] tmp83_fu_3282_p2;
wire   [2:0] tmp83_cast_fu_3288_p1;
wire   [2:0] tmp81_cast_fu_3272_p1;
wire   [1:0] p_Result_74_cast_fu_2360_p1;
wire   [1:0] p_Result_76_cast_fu_2400_p1;
wire   [1:0] tmp84_fu_3298_p2;
wire   [1:0] p_Result_72_cast_fu_2320_p1;
wire   [1:0] tmp87_fu_3304_p2;
wire   [1:0] p_Result_80_cast_fu_2480_p1;
wire   [1:0] p_Result_82_cast_fu_2520_p1;
wire   [1:0] tmp88_fu_3314_p2;
wire   [1:0] p_Result_78_cast_fu_2440_p1;
wire   [1:0] tmp89_fu_3320_p2;
wire   [2:0] tmp89_cast_fu_3326_p1;
wire   [2:0] tmp87_cast_fu_3310_p1;
wire   [1:0] p_Result_86_cast_fu_2600_p1;
wire   [1:0] p_Result_88_cast_fu_2640_p1;
wire   [1:0] tmp90_fu_3336_p2;
wire   [1:0] p_Result_84_cast_fu_2560_p1;
wire   [1:0] p_Result_90_cast_fu_2680_p1;
wire   [1:0] p_Result_92_cast_fu_2720_p1;
wire   [1:0] p_Result_94_cast_fu_2760_p1;
wire   [1:0] p_Result_96_cast_fu_2800_p1;
wire  signed [13:0] tmp7_cast_fu_3363_p1;
wire  signed [13:0] tmp5_cast_fu_3360_p1;
wire   [13:0] tmp4_fu_3366_p2;
wire  signed [13:0] tmp12_cast_fu_3379_p1;
wire  signed [13:0] tmp10_cast_fu_3376_p1;
wire   [13:0] tmp9_fu_3382_p2;
wire  signed [14:0] tmp9_cast_fu_3388_p1;
wire  signed [14:0] tmp4_cast_fu_3372_p1;
wire   [14:0] tmp3_fu_3392_p2;
wire  signed [13:0] tmp18_cast_fu_3405_p1;
wire  signed [13:0] tmp16_cast_fu_3402_p1;
wire   [13:0] tmp15_fu_3408_p2;
wire  signed [13:0] tmp23_cast_fu_3421_p1;
wire  signed [13:0] tmp21_cast_fu_3418_p1;
wire   [13:0] tmp20_fu_3424_p2;
wire  signed [14:0] tmp20_cast_fu_3430_p1;
wire  signed [14:0] tmp15_cast_fu_3414_p1;
wire   [14:0] tmp14_fu_3434_p2;
wire  signed [15:0] tmp14_cast_fu_3440_p1;
wire  signed [15:0] tmp3_cast_fu_3398_p1;
wire  signed [13:0] tmp30_cast_fu_3453_p1;
wire  signed [13:0] tmp28_cast_fu_3450_p1;
wire   [13:0] tmp27_fu_3456_p2;
wire  signed [13:0] tmp35_cast_fu_3469_p1;
wire  signed [13:0] tmp33_cast_fu_3466_p1;
wire   [13:0] tmp32_fu_3472_p2;
wire  signed [14:0] tmp32_cast_fu_3478_p1;
wire  signed [14:0] tmp27_cast_fu_3462_p1;
wire   [14:0] tmp26_fu_3482_p2;
wire  signed [13:0] tmp41_cast_fu_3495_p1;
wire  signed [13:0] tmp39_cast_fu_3492_p1;
wire   [13:0] tmp38_fu_3498_p2;
wire  signed [13:0] tmp46_cast_fu_3511_p1;
wire  signed [13:0] tmp44_cast_fu_3508_p1;
wire   [13:0] tmp43_fu_3514_p2;
wire  signed [14:0] tmp43_cast_fu_3520_p1;
wire  signed [14:0] tmp38_cast_fu_3504_p1;
wire   [14:0] tmp37_fu_3524_p2;
wire  signed [15:0] tmp37_cast_fu_3530_p1;
wire  signed [15:0] tmp26_cast_fu_3488_p1;
wire   [3:0] tmp57_cast_fu_3543_p1;
wire   [3:0] tmp52_cast_fu_3540_p1;
wire   [3:0] tmp51_fu_3546_p2;
wire   [3:0] tmp68_cast_fu_3559_p1;
wire   [3:0] tmp63_cast_fu_3556_p1;
wire   [3:0] tmp62_fu_3562_p2;
wire   [4:0] tmp62_cast_fu_3568_p1;
wire   [4:0] tmp51_cast_fu_3552_p1;
wire   [4:0] tmp50_fu_3572_p2;
wire   [3:0] tmp80_cast_fu_3585_p1;
wire   [3:0] tmp75_cast_fu_3582_p1;
wire   [3:0] tmp74_fu_3588_p2;
wire   [2:0] tmp96_cast_fu_3607_p1;
wire   [2:0] tmp95_cast_fu_3604_p1;
wire   [2:0] tmp94_fu_3610_p2;
wire   [2:0] tmp92_cast_fu_3601_p1;
wire   [2:0] tmp91_fu_3616_p2;
wire   [3:0] tmp91_cast_fu_3622_p1;
wire   [3:0] tmp86_cast_fu_3598_p1;
wire   [3:0] tmp85_fu_3626_p2;
wire   [4:0] tmp85_cast_fu_3632_p1;
wire   [4:0] tmp74_cast_fu_3594_p1;
wire   [4:0] tmp73_fu_3636_p2;
wire   [5:0] tmp73_cast_fu_3642_p1;
wire   [5:0] tmp50_cast_fu_3578_p1;
wire   [15:0] tmp49_cast_fu_3656_p1;
wire   [15:0] tmp1_fu_3652_p2;
wire   [0:0] storemerge1_fu_3665_p0;
wire   [15:0] p_Val2_191_6_fu_3659_p2;
reg   [3:0] ap_NS_fsm;
wire   [15:0] p_Val2_10_fu_1252_p00;
wire   [15:0] p_Val2_11_fu_1292_p00;
wire   [15:0] p_Val2_12_fu_1332_p00;
wire   [15:0] p_Val2_13_fu_1372_p00;
wire   [15:0] p_Val2_14_fu_1412_p00;
wire   [15:0] p_Val2_15_fu_1452_p00;
wire   [15:0] p_Val2_16_fu_1492_p00;
wire   [15:0] p_Val2_17_fu_1532_p00;
wire   [15:0] p_Val2_18_fu_1572_p00;
wire   [15:0] p_Val2_19_fu_1612_p00;
wire   [15:0] p_Val2_1_fu_892_p00;
wire   [15:0] p_Val2_20_fu_1652_p00;
wire   [15:0] p_Val2_21_fu_1692_p00;
wire   [15:0] p_Val2_22_fu_1732_p00;
wire   [15:0] p_Val2_23_fu_1772_p00;
wire   [15:0] p_Val2_24_fu_1812_p00;
wire   [15:0] p_Val2_25_fu_1852_p00;
wire   [15:0] p_Val2_26_fu_1892_p00;
wire   [15:0] p_Val2_27_fu_1932_p00;
wire   [15:0] p_Val2_28_fu_1972_p00;
wire   [15:0] p_Val2_29_fu_2012_p00;
wire   [15:0] p_Val2_2_fu_932_p00;
wire   [15:0] p_Val2_30_fu_2052_p00;
wire   [15:0] p_Val2_31_fu_2092_p00;
wire   [15:0] p_Val2_32_fu_2132_p00;
wire   [15:0] p_Val2_33_fu_2172_p00;
wire   [15:0] p_Val2_34_fu_2212_p00;
wire   [15:0] p_Val2_35_fu_2252_p00;
wire   [15:0] p_Val2_36_fu_2292_p00;
wire   [15:0] p_Val2_37_fu_2332_p00;
wire   [15:0] p_Val2_38_fu_2372_p00;
wire   [15:0] p_Val2_39_fu_2412_p00;
wire   [15:0] p_Val2_3_fu_972_p00;
wire   [15:0] p_Val2_40_fu_2452_p00;
wire   [15:0] p_Val2_41_fu_2492_p00;
wire   [15:0] p_Val2_42_fu_2532_p00;
wire   [15:0] p_Val2_43_fu_2572_p00;
wire   [15:0] p_Val2_44_fu_2612_p00;
wire   [15:0] p_Val2_45_fu_2652_p00;
wire   [15:0] p_Val2_46_fu_2692_p00;
wire   [15:0] p_Val2_47_fu_2732_p00;
wire   [15:0] p_Val2_48_fu_2772_p00;
wire   [15:0] p_Val2_4_fu_1012_p00;
wire   [15:0] p_Val2_5_fu_1052_p00;
wire   [15:0] p_Val2_6_fu_1092_p00;
wire   [15:0] p_Val2_7_fu_1132_p00;
wire   [15:0] p_Val2_8_fu_1172_p00;
wire   [15:0] p_Val2_9_fu_1212_p00;
wire   [15:0] p_Val2_s_fu_852_p00;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (sop_enable_read_read_fu_236_p2 == 1'd1))) begin
        tmp10_reg_3689 <= tmp10_fu_2846_p2;
        tmp12_reg_3694 <= tmp12_fu_2862_p2;
        tmp16_reg_3699 <= tmp16_fu_2878_p2;
        tmp18_reg_3704 <= tmp18_fu_2894_p2;
        tmp21_reg_3709 <= tmp21_fu_2910_p2;
        tmp23_reg_3714 <= tmp23_fu_2926_p2;
        tmp28_reg_3719 <= tmp28_fu_2942_p2;
        tmp30_reg_3724 <= tmp30_fu_2958_p2;
        tmp33_reg_3729 <= tmp33_fu_2974_p2;
        tmp35_reg_3734 <= tmp35_fu_2990_p2;
        tmp39_reg_3739 <= tmp39_fu_3006_p2;
        tmp41_reg_3744 <= tmp41_fu_3022_p2;
        tmp44_reg_3749 <= tmp44_fu_3038_p2;
        tmp46_reg_3754 <= tmp46_fu_3064_p2;
        tmp52_reg_3759 <= tmp52_fu_3102_p2;
        tmp57_reg_3764 <= tmp57_fu_3140_p2;
        tmp5_reg_3679 <= tmp5_fu_2814_p2;
        tmp63_reg_3769 <= tmp63_fu_3178_p2;
        tmp68_reg_3774 <= tmp68_fu_3216_p2;
        tmp75_reg_3779 <= tmp75_fu_3254_p2;
        tmp7_reg_3684 <= tmp7_fu_2830_p2;
        tmp80_reg_3784 <= tmp80_fu_3292_p2;
        tmp86_reg_3789 <= tmp86_fu_3330_p2;
        tmp92_reg_3794 <= tmp92_fu_3342_p2;
        tmp93_reg_3799 <= tmp93_fu_3348_p2;
        tmp95_reg_3804 <= tmp95_fu_3354_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (sop_enable_read_read_fu_236_p2 == 1'd1))) begin
        tmp25_reg_3814 <= tmp25_fu_3534_p2;
        tmp2_reg_3809 <= tmp2_fu_3444_p2;
        tmp49_reg_3819 <= tmp49_fu_3646_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out_val_V_ap_vld = 1'b1;
    end else begin
        out_val_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out_valid_ap_vld = 1'b1;
    end else begin
        out_valid_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign out_val_V = ((storemerge1_fu_3665_p0[0:0] === 1'b1) ? p_Val2_191_6_fu_3659_p2 : 16'd0);

assign out_valid = sop_enable;

assign p_Result_10_cast_fu_1080_p1 = tmp_54_fu_1072_p3;

assign p_Result_12_cast_fu_1120_p1 = tmp_55_fu_1112_p3;

assign p_Result_14_cast_fu_1160_p1 = tmp_56_fu_1152_p3;

assign p_Result_16_cast_fu_1200_p1 = tmp_57_fu_1192_p3;

assign p_Result_18_cast_fu_1240_p1 = tmp_58_fu_1232_p3;

assign p_Result_1_cast_fu_880_p1 = tmp_49_fu_872_p3;

assign p_Result_20_cast_fu_1280_p1 = tmp_59_fu_1272_p3;

assign p_Result_22_cast_fu_1320_p1 = tmp_60_fu_1312_p3;

assign p_Result_24_cast_fu_1360_p1 = tmp_61_fu_1352_p3;

assign p_Result_26_cast_fu_1400_p1 = tmp_62_fu_1392_p3;

assign p_Result_28_cast_fu_1440_p1 = tmp_63_fu_1432_p3;

assign p_Result_30_cast_fu_1480_p1 = tmp_64_fu_1472_p3;

assign p_Result_32_cast_fu_1520_p1 = tmp_65_fu_1512_p3;

assign p_Result_34_cast_fu_1560_p1 = tmp_66_fu_1552_p3;

assign p_Result_36_cast_fu_1600_p1 = tmp_67_fu_1592_p3;

assign p_Result_38_cast_fu_1640_p1 = tmp_68_fu_1632_p3;

assign p_Result_3_cast_fu_920_p1 = tmp_50_fu_912_p3;

assign p_Result_40_cast_fu_1680_p1 = tmp_69_fu_1672_p3;

assign p_Result_42_cast_fu_1720_p1 = tmp_70_fu_1712_p3;

assign p_Result_44_cast_fu_1760_p1 = tmp_71_fu_1752_p3;

assign p_Result_46_cast_fu_1800_p1 = tmp_72_fu_1792_p3;

assign p_Result_48_cast_fu_1840_p1 = tmp_73_fu_1832_p3;

assign p_Result_50_cast_fu_1880_p1 = tmp_74_fu_1872_p3;

assign p_Result_52_cast_fu_1920_p1 = tmp_75_fu_1912_p3;

assign p_Result_54_cast_fu_1960_p1 = tmp_76_fu_1952_p3;

assign p_Result_56_cast_fu_2000_p1 = tmp_77_fu_1992_p3;

assign p_Result_58_cast_fu_2040_p1 = tmp_78_fu_2032_p3;

assign p_Result_5_cast_fu_960_p1 = tmp_51_fu_952_p3;

assign p_Result_60_cast_fu_2080_p1 = tmp_79_fu_2072_p3;

assign p_Result_62_cast_fu_2120_p1 = tmp_80_fu_2112_p3;

assign p_Result_64_cast_fu_2160_p1 = tmp_81_fu_2152_p3;

assign p_Result_66_cast_fu_2200_p1 = tmp_82_fu_2192_p3;

assign p_Result_68_cast_fu_2240_p1 = tmp_83_fu_2232_p3;

assign p_Result_70_cast_fu_2280_p1 = tmp_84_fu_2272_p3;

assign p_Result_72_cast_fu_2320_p1 = tmp_85_fu_2312_p3;

assign p_Result_74_cast_fu_2360_p1 = tmp_86_fu_2352_p3;

assign p_Result_76_cast_fu_2400_p1 = tmp_87_fu_2392_p3;

assign p_Result_78_cast_fu_2440_p1 = tmp_88_fu_2432_p3;

assign p_Result_7_cast_fu_1000_p1 = tmp_52_fu_992_p3;

assign p_Result_80_cast_fu_2480_p1 = tmp_89_fu_2472_p3;

assign p_Result_82_cast_fu_2520_p1 = tmp_90_fu_2512_p3;

assign p_Result_84_cast_fu_2560_p1 = tmp_91_fu_2552_p3;

assign p_Result_86_cast_fu_2600_p1 = tmp_92_fu_2592_p3;

assign p_Result_88_cast_fu_2640_p1 = tmp_93_fu_2632_p3;

assign p_Result_90_cast_fu_2680_p1 = tmp_94_fu_2672_p3;

assign p_Result_92_cast_fu_2720_p1 = tmp_95_fu_2712_p3;

assign p_Result_94_cast_fu_2760_p1 = tmp_96_fu_2752_p3;

assign p_Result_96_cast_fu_2800_p1 = tmp_97_fu_2792_p3;

assign p_Result_9_cast_fu_1040_p1 = tmp_53_fu_1032_p3;

assign p_Val2_100_cast_fu_2188_p1 = $signed(tmp_33_fu_2178_p4);

assign p_Val2_103_cast_fu_2228_p1 = $signed(tmp_34_fu_2218_p4);

assign p_Val2_106_cast_fu_2268_p1 = $signed(tmp_35_fu_2258_p4);

assign p_Val2_109_cast_fu_2308_p1 = $signed(tmp_36_fu_2298_p4);

assign p_Val2_10_cast_fu_988_p1 = $signed(tmp_s_fu_978_p4);

assign p_Val2_10_fu_1252_p0 = p_Val2_10_fu_1252_p00;

assign p_Val2_10_fu_1252_p00 = pixel_window_10_V;

assign p_Val2_10_fu_1252_p1 = kernel_patch_10_V;

assign p_Val2_10_fu_1252_p2 = ($signed({{1'b0}, {p_Val2_10_fu_1252_p0}}) * $signed(p_Val2_10_fu_1252_p1));

assign p_Val2_112_cast_fu_2348_p1 = $signed(tmp_37_fu_2338_p4);

assign p_Val2_115_cast_fu_2388_p1 = $signed(tmp_38_fu_2378_p4);

assign p_Val2_118_cast_fu_2428_p1 = $signed(tmp_39_fu_2418_p4);

assign p_Val2_11_fu_1292_p0 = p_Val2_11_fu_1292_p00;

assign p_Val2_11_fu_1292_p00 = pixel_window_11_V;

assign p_Val2_11_fu_1292_p1 = kernel_patch_11_V;

assign p_Val2_11_fu_1292_p2 = ($signed({{1'b0}, {p_Val2_11_fu_1292_p0}}) * $signed(p_Val2_11_fu_1292_p1));

assign p_Val2_121_cast_fu_2468_p1 = $signed(tmp_40_fu_2458_p4);

assign p_Val2_124_cast_fu_2508_p1 = $signed(tmp_41_fu_2498_p4);

assign p_Val2_127_cast_fu_2548_p1 = $signed(tmp_42_fu_2538_p4);

assign p_Val2_12_fu_1332_p0 = p_Val2_12_fu_1332_p00;

assign p_Val2_12_fu_1332_p00 = pixel_window_12_V;

assign p_Val2_12_fu_1332_p1 = kernel_patch_12_V;

assign p_Val2_12_fu_1332_p2 = ($signed({{1'b0}, {p_Val2_12_fu_1332_p0}}) * $signed(p_Val2_12_fu_1332_p1));

assign p_Val2_130_cast_fu_2588_p1 = $signed(tmp_43_fu_2578_p4);

assign p_Val2_133_cast_fu_2628_p1 = $signed(tmp_44_fu_2618_p4);

assign p_Val2_136_cast_fu_2668_p1 = $signed(tmp_45_fu_2658_p4);

assign p_Val2_139_cast_fu_2708_p1 = $signed(tmp_46_fu_2698_p4);

assign p_Val2_13_cast_fu_1028_p1 = $signed(tmp_5_fu_1018_p4);

assign p_Val2_13_fu_1372_p0 = p_Val2_13_fu_1372_p00;

assign p_Val2_13_fu_1372_p00 = pixel_window_13_V;

assign p_Val2_13_fu_1372_p1 = kernel_patch_13_V;

assign p_Val2_13_fu_1372_p2 = ($signed({{1'b0}, {p_Val2_13_fu_1372_p0}}) * $signed(p_Val2_13_fu_1372_p1));

assign p_Val2_142_cast_fu_2748_p1 = $signed(tmp_47_fu_2738_p4);

assign p_Val2_145_cast_fu_2788_p1 = $signed(tmp_48_fu_2778_p4);

assign p_Val2_14_fu_1412_p0 = p_Val2_14_fu_1412_p00;

assign p_Val2_14_fu_1412_p00 = pixel_window_14_V;

assign p_Val2_14_fu_1412_p1 = kernel_patch_14_V;

assign p_Val2_14_fu_1412_p2 = ($signed({{1'b0}, {p_Val2_14_fu_1412_p0}}) * $signed(p_Val2_14_fu_1412_p1));

assign p_Val2_15_fu_1452_p0 = p_Val2_15_fu_1452_p00;

assign p_Val2_15_fu_1452_p00 = pixel_window_15_V;

assign p_Val2_15_fu_1452_p1 = kernel_patch_15_V;

assign p_Val2_15_fu_1452_p2 = ($signed({{1'b0}, {p_Val2_15_fu_1452_p0}}) * $signed(p_Val2_15_fu_1452_p1));

assign p_Val2_16_cast_fu_1068_p1 = $signed(tmp_2_fu_1058_p4);

assign p_Val2_16_fu_1492_p0 = p_Val2_16_fu_1492_p00;

assign p_Val2_16_fu_1492_p00 = pixel_window_16_V;

assign p_Val2_16_fu_1492_p1 = kernel_patch_16_V;

assign p_Val2_16_fu_1492_p2 = ($signed({{1'b0}, {p_Val2_16_fu_1492_p0}}) * $signed(p_Val2_16_fu_1492_p1));

assign p_Val2_17_fu_1532_p0 = p_Val2_17_fu_1532_p00;

assign p_Val2_17_fu_1532_p00 = pixel_window_17_V;

assign p_Val2_17_fu_1532_p1 = kernel_patch_17_V;

assign p_Val2_17_fu_1532_p2 = ($signed({{1'b0}, {p_Val2_17_fu_1532_p0}}) * $signed(p_Val2_17_fu_1532_p1));

assign p_Val2_18_fu_1572_p0 = p_Val2_18_fu_1572_p00;

assign p_Val2_18_fu_1572_p00 = pixel_window_18_V;

assign p_Val2_18_fu_1572_p1 = kernel_patch_18_V;

assign p_Val2_18_fu_1572_p2 = ($signed({{1'b0}, {p_Val2_18_fu_1572_p0}}) * $signed(p_Val2_18_fu_1572_p1));

assign p_Val2_191_6_fu_3659_p2 = (tmp49_cast_fu_3656_p1 + tmp1_fu_3652_p2);

assign p_Val2_19_cast_fu_1108_p1 = $signed(tmp_3_fu_1098_p4);

assign p_Val2_19_fu_1612_p0 = p_Val2_19_fu_1612_p00;

assign p_Val2_19_fu_1612_p00 = pixel_window_19_V;

assign p_Val2_19_fu_1612_p1 = kernel_patch_19_V;

assign p_Val2_19_fu_1612_p2 = ($signed({{1'b0}, {p_Val2_19_fu_1612_p0}}) * $signed(p_Val2_19_fu_1612_p1));

assign p_Val2_1_cast_fu_868_p1 = $signed(tmp_1_fu_858_p4);

assign p_Val2_1_fu_892_p0 = p_Val2_1_fu_892_p00;

assign p_Val2_1_fu_892_p00 = pixel_window_1_V;

assign p_Val2_1_fu_892_p1 = kernel_patch_1_V;

assign p_Val2_1_fu_892_p2 = ($signed({{1'b0}, {p_Val2_1_fu_892_p0}}) * $signed(p_Val2_1_fu_892_p1));

assign p_Val2_20_fu_1652_p0 = p_Val2_20_fu_1652_p00;

assign p_Val2_20_fu_1652_p00 = pixel_window_20_V;

assign p_Val2_20_fu_1652_p1 = kernel_patch_20_V;

assign p_Val2_20_fu_1652_p2 = ($signed({{1'b0}, {p_Val2_20_fu_1652_p0}}) * $signed(p_Val2_20_fu_1652_p1));

assign p_Val2_21_fu_1692_p0 = p_Val2_21_fu_1692_p00;

assign p_Val2_21_fu_1692_p00 = pixel_window_21_V;

assign p_Val2_21_fu_1692_p1 = kernel_patch_21_V;

assign p_Val2_21_fu_1692_p2 = ($signed({{1'b0}, {p_Val2_21_fu_1692_p0}}) * $signed(p_Val2_21_fu_1692_p1));

assign p_Val2_22_cast_fu_1148_p1 = $signed(tmp_6_fu_1138_p4);

assign p_Val2_22_fu_1732_p0 = p_Val2_22_fu_1732_p00;

assign p_Val2_22_fu_1732_p00 = pixel_window_22_V;

assign p_Val2_22_fu_1732_p1 = kernel_patch_22_V;

assign p_Val2_22_fu_1732_p2 = ($signed({{1'b0}, {p_Val2_22_fu_1732_p0}}) * $signed(p_Val2_22_fu_1732_p1));

assign p_Val2_23_fu_1772_p0 = p_Val2_23_fu_1772_p00;

assign p_Val2_23_fu_1772_p00 = pixel_window_23_V;

assign p_Val2_23_fu_1772_p1 = kernel_patch_23_V;

assign p_Val2_23_fu_1772_p2 = ($signed({{1'b0}, {p_Val2_23_fu_1772_p0}}) * $signed(p_Val2_23_fu_1772_p1));

assign p_Val2_24_fu_1812_p0 = p_Val2_24_fu_1812_p00;

assign p_Val2_24_fu_1812_p00 = pixel_window_24_V;

assign p_Val2_24_fu_1812_p1 = kernel_patch_24_V;

assign p_Val2_24_fu_1812_p2 = ($signed({{1'b0}, {p_Val2_24_fu_1812_p0}}) * $signed(p_Val2_24_fu_1812_p1));

assign p_Val2_25_cast_fu_1188_p1 = $signed(tmp_8_fu_1178_p4);

assign p_Val2_25_fu_1852_p0 = p_Val2_25_fu_1852_p00;

assign p_Val2_25_fu_1852_p00 = pixel_window_25_V;

assign p_Val2_25_fu_1852_p1 = kernel_patch_25_V;

assign p_Val2_25_fu_1852_p2 = ($signed({{1'b0}, {p_Val2_25_fu_1852_p0}}) * $signed(p_Val2_25_fu_1852_p1));

assign p_Val2_26_fu_1892_p0 = p_Val2_26_fu_1892_p00;

assign p_Val2_26_fu_1892_p00 = pixel_window_26_V;

assign p_Val2_26_fu_1892_p1 = kernel_patch_26_V;

assign p_Val2_26_fu_1892_p2 = ($signed({{1'b0}, {p_Val2_26_fu_1892_p0}}) * $signed(p_Val2_26_fu_1892_p1));

assign p_Val2_27_fu_1932_p0 = p_Val2_27_fu_1932_p00;

assign p_Val2_27_fu_1932_p00 = pixel_window_27_V;

assign p_Val2_27_fu_1932_p1 = kernel_patch_27_V;

assign p_Val2_27_fu_1932_p2 = ($signed({{1'b0}, {p_Val2_27_fu_1932_p0}}) * $signed(p_Val2_27_fu_1932_p1));

assign p_Val2_28_cast_fu_1228_p1 = $signed(tmp_9_fu_1218_p4);

assign p_Val2_28_fu_1972_p0 = p_Val2_28_fu_1972_p00;

assign p_Val2_28_fu_1972_p00 = pixel_window_28_V;

assign p_Val2_28_fu_1972_p1 = kernel_patch_28_V;

assign p_Val2_28_fu_1972_p2 = ($signed({{1'b0}, {p_Val2_28_fu_1972_p0}}) * $signed(p_Val2_28_fu_1972_p1));

assign p_Val2_29_fu_2012_p0 = p_Val2_29_fu_2012_p00;

assign p_Val2_29_fu_2012_p00 = pixel_window_29_V;

assign p_Val2_29_fu_2012_p1 = kernel_patch_29_V;

assign p_Val2_29_fu_2012_p2 = ($signed({{1'b0}, {p_Val2_29_fu_2012_p0}}) * $signed(p_Val2_29_fu_2012_p1));

assign p_Val2_2_fu_932_p0 = p_Val2_2_fu_932_p00;

assign p_Val2_2_fu_932_p00 = pixel_window_2_V;

assign p_Val2_2_fu_932_p1 = kernel_patch_2_V;

assign p_Val2_2_fu_932_p2 = ($signed({{1'b0}, {p_Val2_2_fu_932_p0}}) * $signed(p_Val2_2_fu_932_p1));

assign p_Val2_30_fu_2052_p0 = p_Val2_30_fu_2052_p00;

assign p_Val2_30_fu_2052_p00 = pixel_window_30_V;

assign p_Val2_30_fu_2052_p1 = kernel_patch_30_V;

assign p_Val2_30_fu_2052_p2 = ($signed({{1'b0}, {p_Val2_30_fu_2052_p0}}) * $signed(p_Val2_30_fu_2052_p1));

assign p_Val2_31_cast_fu_1268_p1 = $signed(tmp_10_fu_1258_p4);

assign p_Val2_31_fu_2092_p0 = p_Val2_31_fu_2092_p00;

assign p_Val2_31_fu_2092_p00 = pixel_window_31_V;

assign p_Val2_31_fu_2092_p1 = kernel_patch_31_V;

assign p_Val2_31_fu_2092_p2 = ($signed({{1'b0}, {p_Val2_31_fu_2092_p0}}) * $signed(p_Val2_31_fu_2092_p1));

assign p_Val2_32_fu_2132_p0 = p_Val2_32_fu_2132_p00;

assign p_Val2_32_fu_2132_p00 = pixel_window_32_V;

assign p_Val2_32_fu_2132_p1 = kernel_patch_32_V;

assign p_Val2_32_fu_2132_p2 = ($signed({{1'b0}, {p_Val2_32_fu_2132_p0}}) * $signed(p_Val2_32_fu_2132_p1));

assign p_Val2_33_fu_2172_p0 = p_Val2_33_fu_2172_p00;

assign p_Val2_33_fu_2172_p00 = pixel_window_33_V;

assign p_Val2_33_fu_2172_p1 = kernel_patch_33_V;

assign p_Val2_33_fu_2172_p2 = ($signed({{1'b0}, {p_Val2_33_fu_2172_p0}}) * $signed(p_Val2_33_fu_2172_p1));

assign p_Val2_34_cast_fu_1308_p1 = $signed(tmp_11_fu_1298_p4);

assign p_Val2_34_fu_2212_p0 = p_Val2_34_fu_2212_p00;

assign p_Val2_34_fu_2212_p00 = pixel_window_34_V;

assign p_Val2_34_fu_2212_p1 = kernel_patch_34_V;

assign p_Val2_34_fu_2212_p2 = ($signed({{1'b0}, {p_Val2_34_fu_2212_p0}}) * $signed(p_Val2_34_fu_2212_p1));

assign p_Val2_35_fu_2252_p0 = p_Val2_35_fu_2252_p00;

assign p_Val2_35_fu_2252_p00 = pixel_window_35_V;

assign p_Val2_35_fu_2252_p1 = kernel_patch_35_V;

assign p_Val2_35_fu_2252_p2 = ($signed({{1'b0}, {p_Val2_35_fu_2252_p0}}) * $signed(p_Val2_35_fu_2252_p1));

assign p_Val2_36_fu_2292_p0 = p_Val2_36_fu_2292_p00;

assign p_Val2_36_fu_2292_p00 = pixel_window_36_V;

assign p_Val2_36_fu_2292_p1 = kernel_patch_36_V;

assign p_Val2_36_fu_2292_p2 = ($signed({{1'b0}, {p_Val2_36_fu_2292_p0}}) * $signed(p_Val2_36_fu_2292_p1));

assign p_Val2_37_cast_fu_1348_p1 = $signed(tmp_12_fu_1338_p4);

assign p_Val2_37_fu_2332_p0 = p_Val2_37_fu_2332_p00;

assign p_Val2_37_fu_2332_p00 = pixel_window_37_V;

assign p_Val2_37_fu_2332_p1 = kernel_patch_37_V;

assign p_Val2_37_fu_2332_p2 = ($signed({{1'b0}, {p_Val2_37_fu_2332_p0}}) * $signed(p_Val2_37_fu_2332_p1));

assign p_Val2_38_fu_2372_p0 = p_Val2_38_fu_2372_p00;

assign p_Val2_38_fu_2372_p00 = pixel_window_38_V;

assign p_Val2_38_fu_2372_p1 = kernel_patch_38_V;

assign p_Val2_38_fu_2372_p2 = ($signed({{1'b0}, {p_Val2_38_fu_2372_p0}}) * $signed(p_Val2_38_fu_2372_p1));

assign p_Val2_39_fu_2412_p0 = p_Val2_39_fu_2412_p00;

assign p_Val2_39_fu_2412_p00 = pixel_window_39_V;

assign p_Val2_39_fu_2412_p1 = kernel_patch_39_V;

assign p_Val2_39_fu_2412_p2 = ($signed({{1'b0}, {p_Val2_39_fu_2412_p0}}) * $signed(p_Val2_39_fu_2412_p1));

assign p_Val2_3_fu_972_p0 = p_Val2_3_fu_972_p00;

assign p_Val2_3_fu_972_p00 = pixel_window_3_V;

assign p_Val2_3_fu_972_p1 = kernel_patch_3_V;

assign p_Val2_3_fu_972_p2 = ($signed({{1'b0}, {p_Val2_3_fu_972_p0}}) * $signed(p_Val2_3_fu_972_p1));

assign p_Val2_40_cast_fu_1388_p1 = $signed(tmp_13_fu_1378_p4);

assign p_Val2_40_fu_2452_p0 = p_Val2_40_fu_2452_p00;

assign p_Val2_40_fu_2452_p00 = pixel_window_40_V;

assign p_Val2_40_fu_2452_p1 = kernel_patch_40_V;

assign p_Val2_40_fu_2452_p2 = ($signed({{1'b0}, {p_Val2_40_fu_2452_p0}}) * $signed(p_Val2_40_fu_2452_p1));

assign p_Val2_41_fu_2492_p0 = p_Val2_41_fu_2492_p00;

assign p_Val2_41_fu_2492_p00 = pixel_window_41_V;

assign p_Val2_41_fu_2492_p1 = kernel_patch_41_V;

assign p_Val2_41_fu_2492_p2 = ($signed({{1'b0}, {p_Val2_41_fu_2492_p0}}) * $signed(p_Val2_41_fu_2492_p1));

assign p_Val2_42_fu_2532_p0 = p_Val2_42_fu_2532_p00;

assign p_Val2_42_fu_2532_p00 = pixel_window_42_V;

assign p_Val2_42_fu_2532_p1 = kernel_patch_42_V;

assign p_Val2_42_fu_2532_p2 = ($signed({{1'b0}, {p_Val2_42_fu_2532_p0}}) * $signed(p_Val2_42_fu_2532_p1));

assign p_Val2_43_cast_fu_1428_p1 = $signed(tmp_14_fu_1418_p4);

assign p_Val2_43_fu_2572_p0 = p_Val2_43_fu_2572_p00;

assign p_Val2_43_fu_2572_p00 = pixel_window_43_V;

assign p_Val2_43_fu_2572_p1 = kernel_patch_43_V;

assign p_Val2_43_fu_2572_p2 = ($signed({{1'b0}, {p_Val2_43_fu_2572_p0}}) * $signed(p_Val2_43_fu_2572_p1));

assign p_Val2_44_fu_2612_p0 = p_Val2_44_fu_2612_p00;

assign p_Val2_44_fu_2612_p00 = pixel_window_44_V;

assign p_Val2_44_fu_2612_p1 = kernel_patch_44_V;

assign p_Val2_44_fu_2612_p2 = ($signed({{1'b0}, {p_Val2_44_fu_2612_p0}}) * $signed(p_Val2_44_fu_2612_p1));

assign p_Val2_45_fu_2652_p0 = p_Val2_45_fu_2652_p00;

assign p_Val2_45_fu_2652_p00 = pixel_window_45_V;

assign p_Val2_45_fu_2652_p1 = kernel_patch_45_V;

assign p_Val2_45_fu_2652_p2 = ($signed({{1'b0}, {p_Val2_45_fu_2652_p0}}) * $signed(p_Val2_45_fu_2652_p1));

assign p_Val2_46_cast_fu_1468_p1 = $signed(tmp_15_fu_1458_p4);

assign p_Val2_46_fu_2692_p0 = p_Val2_46_fu_2692_p00;

assign p_Val2_46_fu_2692_p00 = pixel_window_46_V;

assign p_Val2_46_fu_2692_p1 = kernel_patch_46_V;

assign p_Val2_46_fu_2692_p2 = ($signed({{1'b0}, {p_Val2_46_fu_2692_p0}}) * $signed(p_Val2_46_fu_2692_p1));

assign p_Val2_47_fu_2732_p0 = p_Val2_47_fu_2732_p00;

assign p_Val2_47_fu_2732_p00 = pixel_window_47_V;

assign p_Val2_47_fu_2732_p1 = kernel_patch_47_V;

assign p_Val2_47_fu_2732_p2 = ($signed({{1'b0}, {p_Val2_47_fu_2732_p0}}) * $signed(p_Val2_47_fu_2732_p1));

assign p_Val2_48_fu_2772_p0 = p_Val2_48_fu_2772_p00;

assign p_Val2_48_fu_2772_p00 = pixel_window_48_V;

assign p_Val2_48_fu_2772_p1 = kernel_patch_48_V;

assign p_Val2_48_fu_2772_p2 = ($signed({{1'b0}, {p_Val2_48_fu_2772_p0}}) * $signed(p_Val2_48_fu_2772_p1));

assign p_Val2_49_cast_fu_1508_p1 = $signed(tmp_16_fu_1498_p4);

assign p_Val2_4_cast_fu_908_p1 = $signed(tmp_4_fu_898_p4);

assign p_Val2_4_fu_1012_p0 = p_Val2_4_fu_1012_p00;

assign p_Val2_4_fu_1012_p00 = pixel_window_4_V;

assign p_Val2_4_fu_1012_p1 = kernel_patch_4_V;

assign p_Val2_4_fu_1012_p2 = ($signed({{1'b0}, {p_Val2_4_fu_1012_p0}}) * $signed(p_Val2_4_fu_1012_p1));

assign p_Val2_52_cast_fu_1548_p1 = $signed(tmp_17_fu_1538_p4);

assign p_Val2_55_cast_fu_1588_p1 = $signed(tmp_18_fu_1578_p4);

assign p_Val2_58_cast_fu_1628_p1 = $signed(tmp_19_fu_1618_p4);

assign p_Val2_5_fu_1052_p0 = p_Val2_5_fu_1052_p00;

assign p_Val2_5_fu_1052_p00 = pixel_window_5_V;

assign p_Val2_5_fu_1052_p1 = kernel_patch_5_V;

assign p_Val2_5_fu_1052_p2 = ($signed({{1'b0}, {p_Val2_5_fu_1052_p0}}) * $signed(p_Val2_5_fu_1052_p1));

assign p_Val2_61_cast_fu_1668_p1 = $signed(tmp_20_fu_1658_p4);

assign p_Val2_64_cast_fu_1708_p1 = $signed(tmp_21_fu_1698_p4);

assign p_Val2_67_cast_fu_1748_p1 = $signed(tmp_22_fu_1738_p4);

assign p_Val2_6_fu_1092_p0 = p_Val2_6_fu_1092_p00;

assign p_Val2_6_fu_1092_p00 = pixel_window_6_V;

assign p_Val2_6_fu_1092_p1 = kernel_patch_6_V;

assign p_Val2_6_fu_1092_p2 = ($signed({{1'b0}, {p_Val2_6_fu_1092_p0}}) * $signed(p_Val2_6_fu_1092_p1));

assign p_Val2_70_cast_fu_1788_p1 = $signed(tmp_23_fu_1778_p4);

assign p_Val2_73_cast_fu_1828_p1 = $signed(tmp_24_fu_1818_p4);

assign p_Val2_76_cast_fu_1868_p1 = $signed(tmp_25_fu_1858_p4);

assign p_Val2_79_cast_fu_1908_p1 = $signed(tmp_26_fu_1898_p4);

assign p_Val2_7_cast_fu_948_p1 = $signed(tmp_7_fu_938_p4);

assign p_Val2_7_fu_1132_p0 = p_Val2_7_fu_1132_p00;

assign p_Val2_7_fu_1132_p00 = pixel_window_7_V;

assign p_Val2_7_fu_1132_p1 = kernel_patch_7_V;

assign p_Val2_7_fu_1132_p2 = ($signed({{1'b0}, {p_Val2_7_fu_1132_p0}}) * $signed(p_Val2_7_fu_1132_p1));

assign p_Val2_82_cast_fu_1948_p1 = $signed(tmp_27_fu_1938_p4);

assign p_Val2_85_cast_fu_1988_p1 = $signed(tmp_28_fu_1978_p4);

assign p_Val2_88_cast_fu_2028_p1 = $signed(tmp_29_fu_2018_p4);

assign p_Val2_8_fu_1172_p0 = p_Val2_8_fu_1172_p00;

assign p_Val2_8_fu_1172_p00 = pixel_window_8_V;

assign p_Val2_8_fu_1172_p1 = kernel_patch_8_V;

assign p_Val2_8_fu_1172_p2 = ($signed({{1'b0}, {p_Val2_8_fu_1172_p0}}) * $signed(p_Val2_8_fu_1172_p1));

assign p_Val2_91_cast_fu_2068_p1 = $signed(tmp_30_fu_2058_p4);

assign p_Val2_94_cast_fu_2108_p1 = $signed(tmp_31_fu_2098_p4);

assign p_Val2_97_cast_fu_2148_p1 = $signed(tmp_32_fu_2138_p4);

assign p_Val2_9_fu_1212_p0 = p_Val2_9_fu_1212_p00;

assign p_Val2_9_fu_1212_p00 = pixel_window_9_V;

assign p_Val2_9_fu_1212_p1 = kernel_patch_9_V;

assign p_Val2_9_fu_1212_p2 = ($signed({{1'b0}, {p_Val2_9_fu_1212_p0}}) * $signed(p_Val2_9_fu_1212_p1));

assign p_Val2_s_fu_852_p0 = p_Val2_s_fu_852_p00;

assign p_Val2_s_fu_852_p00 = pixel_window_0_V;

assign p_Val2_s_fu_852_p1 = kernel_patch_0_V;

assign p_Val2_s_fu_852_p2 = ($signed({{1'b0}, {p_Val2_s_fu_852_p0}}) * $signed(p_Val2_s_fu_852_p1));

assign sop_enable_read_read_fu_236_p2 = sop_enable;

assign storemerge1_fu_3665_p0 = sop_enable;

assign tmp10_cast_fu_3376_p1 = $signed(tmp10_reg_3689);

assign tmp10_fu_2846_p2 = ($signed(tmp11_cast_fu_2842_p1) + $signed(p_Val2_22_cast_fu_1148_p1));

assign tmp11_cast_fu_2842_p1 = $signed(tmp_fu_2836_p2);

assign tmp11_fu_2852_p2 = ($signed(p_Val2_34_cast_fu_1308_p1) + $signed(p_Val2_37_cast_fu_1348_p1));

assign tmp12_cast_fu_3379_p1 = $signed(tmp12_reg_3694);

assign tmp12_fu_2862_p2 = ($signed(tmp13_cast_fu_2858_p1) + $signed(p_Val2_31_cast_fu_1268_p1));

assign tmp13_cast_fu_2858_p1 = $signed(tmp11_fu_2852_p2);

assign tmp13_fu_2868_p2 = ($signed(p_Val2_43_cast_fu_1428_p1) + $signed(p_Val2_46_cast_fu_1468_p1));

assign tmp14_cast_fu_3440_p1 = $signed(tmp14_fu_3434_p2);

assign tmp14_fu_3434_p2 = ($signed(tmp20_cast_fu_3430_p1) + $signed(tmp15_cast_fu_3414_p1));

assign tmp15_cast_fu_3414_p1 = $signed(tmp15_fu_3408_p2);

assign tmp15_fu_3408_p2 = ($signed(tmp18_cast_fu_3405_p1) + $signed(tmp16_cast_fu_3402_p1));

assign tmp16_cast_fu_3402_p1 = $signed(tmp16_reg_3699);

assign tmp16_fu_2878_p2 = ($signed(tmp17_cast_fu_2874_p1) + $signed(p_Val2_40_cast_fu_1388_p1));

assign tmp17_cast_fu_2874_p1 = $signed(tmp13_fu_2868_p2);

assign tmp17_fu_2884_p2 = ($signed(p_Val2_52_cast_fu_1548_p1) + $signed(p_Val2_55_cast_fu_1588_p1));

assign tmp18_cast_fu_3405_p1 = $signed(tmp18_reg_3704);

assign tmp18_fu_2894_p2 = ($signed(tmp19_cast_fu_2890_p1) + $signed(p_Val2_49_cast_fu_1508_p1));

assign tmp19_cast_fu_2890_p1 = $signed(tmp17_fu_2884_p2);

assign tmp19_fu_2900_p2 = ($signed(p_Val2_61_cast_fu_1668_p1) + $signed(p_Val2_64_cast_fu_1708_p1));

assign tmp1_fu_3652_p2 = (tmp25_reg_3814 + tmp2_reg_3809);

assign tmp20_cast_fu_3430_p1 = $signed(tmp20_fu_3424_p2);

assign tmp20_fu_3424_p2 = ($signed(tmp23_cast_fu_3421_p1) + $signed(tmp21_cast_fu_3418_p1));

assign tmp21_cast_fu_3418_p1 = $signed(tmp21_reg_3709);

assign tmp21_fu_2910_p2 = ($signed(tmp22_cast_fu_2906_p1) + $signed(p_Val2_58_cast_fu_1628_p1));

assign tmp22_cast_fu_2906_p1 = $signed(tmp19_fu_2900_p2);

assign tmp22_fu_2916_p2 = ($signed(p_Val2_70_cast_fu_1788_p1) + $signed(p_Val2_73_cast_fu_1828_p1));

assign tmp23_cast_fu_3421_p1 = $signed(tmp23_reg_3714);

assign tmp23_fu_2926_p2 = ($signed(tmp24_cast_fu_2922_p1) + $signed(p_Val2_67_cast_fu_1748_p1));

assign tmp24_cast_fu_2922_p1 = $signed(tmp22_fu_2916_p2);

assign tmp24_fu_2932_p2 = ($signed(p_Val2_79_cast_fu_1908_p1) + $signed(p_Val2_82_cast_fu_1948_p1));

assign tmp25_fu_3534_p2 = ($signed(tmp37_cast_fu_3530_p1) + $signed(tmp26_cast_fu_3488_p1));

assign tmp26_cast_fu_3488_p1 = $signed(tmp26_fu_3482_p2);

assign tmp26_fu_3482_p2 = ($signed(tmp32_cast_fu_3478_p1) + $signed(tmp27_cast_fu_3462_p1));

assign tmp27_cast_fu_3462_p1 = $signed(tmp27_fu_3456_p2);

assign tmp27_fu_3456_p2 = ($signed(tmp30_cast_fu_3453_p1) + $signed(tmp28_cast_fu_3450_p1));

assign tmp28_cast_fu_3450_p1 = $signed(tmp28_reg_3719);

assign tmp28_fu_2942_p2 = ($signed(tmp29_cast_fu_2938_p1) + $signed(p_Val2_76_cast_fu_1868_p1));

assign tmp29_cast_fu_2938_p1 = $signed(tmp24_fu_2932_p2);

assign tmp29_fu_2948_p2 = ($signed(p_Val2_88_cast_fu_2028_p1) + $signed(p_Val2_91_cast_fu_2068_p1));

assign tmp2_fu_3444_p2 = ($signed(tmp14_cast_fu_3440_p1) + $signed(tmp3_cast_fu_3398_p1));

assign tmp30_cast_fu_3453_p1 = $signed(tmp30_reg_3724);

assign tmp30_fu_2958_p2 = ($signed(tmp31_cast_fu_2954_p1) + $signed(p_Val2_85_cast_fu_1988_p1));

assign tmp31_cast_fu_2954_p1 = $signed(tmp29_fu_2948_p2);

assign tmp31_fu_2964_p2 = ($signed(p_Val2_97_cast_fu_2148_p1) + $signed(p_Val2_100_cast_fu_2188_p1));

assign tmp32_cast_fu_3478_p1 = $signed(tmp32_fu_3472_p2);

assign tmp32_fu_3472_p2 = ($signed(tmp35_cast_fu_3469_p1) + $signed(tmp33_cast_fu_3466_p1));

assign tmp33_cast_fu_3466_p1 = $signed(tmp33_reg_3729);

assign tmp33_fu_2974_p2 = ($signed(tmp34_cast_fu_2970_p1) + $signed(p_Val2_94_cast_fu_2108_p1));

assign tmp34_cast_fu_2970_p1 = $signed(tmp31_fu_2964_p2);

assign tmp34_fu_2980_p2 = ($signed(p_Val2_106_cast_fu_2268_p1) + $signed(p_Val2_109_cast_fu_2308_p1));

assign tmp35_cast_fu_3469_p1 = $signed(tmp35_reg_3734);

assign tmp35_fu_2990_p2 = ($signed(tmp36_cast_fu_2986_p1) + $signed(p_Val2_103_cast_fu_2228_p1));

assign tmp36_cast_fu_2986_p1 = $signed(tmp34_fu_2980_p2);

assign tmp36_fu_2996_p2 = ($signed(p_Val2_115_cast_fu_2388_p1) + $signed(p_Val2_118_cast_fu_2428_p1));

assign tmp37_cast_fu_3530_p1 = $signed(tmp37_fu_3524_p2);

assign tmp37_fu_3524_p2 = ($signed(tmp43_cast_fu_3520_p1) + $signed(tmp38_cast_fu_3504_p1));

assign tmp38_cast_fu_3504_p1 = $signed(tmp38_fu_3498_p2);

assign tmp38_fu_3498_p2 = ($signed(tmp41_cast_fu_3495_p1) + $signed(tmp39_cast_fu_3492_p1));

assign tmp39_cast_fu_3492_p1 = $signed(tmp39_reg_3739);

assign tmp39_fu_3006_p2 = ($signed(tmp40_cast_fu_3002_p1) + $signed(p_Val2_112_cast_fu_2348_p1));

assign tmp3_cast_fu_3398_p1 = $signed(tmp3_fu_3392_p2);

assign tmp3_fu_3392_p2 = ($signed(tmp9_cast_fu_3388_p1) + $signed(tmp4_cast_fu_3372_p1));

assign tmp40_cast_fu_3002_p1 = $signed(tmp36_fu_2996_p2);

assign tmp40_fu_3012_p2 = ($signed(p_Val2_124_cast_fu_2508_p1) + $signed(p_Val2_127_cast_fu_2548_p1));

assign tmp41_cast_fu_3495_p1 = $signed(tmp41_reg_3744);

assign tmp41_fu_3022_p2 = ($signed(tmp42_cast_fu_3018_p1) + $signed(p_Val2_121_cast_fu_2468_p1));

assign tmp42_cast_fu_3018_p1 = $signed(tmp40_fu_3012_p2);

assign tmp42_fu_3028_p2 = ($signed(p_Val2_133_cast_fu_2628_p1) + $signed(p_Val2_136_cast_fu_2668_p1));

assign tmp43_cast_fu_3520_p1 = $signed(tmp43_fu_3514_p2);

assign tmp43_fu_3514_p2 = ($signed(tmp46_cast_fu_3511_p1) + $signed(tmp44_cast_fu_3508_p1));

assign tmp44_cast_fu_3508_p1 = $signed(tmp44_reg_3749);

assign tmp44_fu_3038_p2 = ($signed(tmp45_cast_fu_3034_p1) + $signed(p_Val2_130_cast_fu_2588_p1));

assign tmp45_cast_fu_3034_p1 = $signed(tmp42_fu_3028_p2);

assign tmp45_fu_3044_p2 = ($signed(p_Val2_139_cast_fu_2708_p1) + $signed(p_Val2_142_cast_fu_2748_p1));

assign tmp46_cast_fu_3511_p1 = $signed(tmp46_reg_3754);

assign tmp46_fu_3064_p2 = ($signed(tmp48_cast_fu_3060_p1) + $signed(tmp47_cast_fu_3050_p1));

assign tmp47_cast_fu_3050_p1 = $signed(tmp45_fu_3044_p2);

assign tmp47_fu_3054_p2 = ($signed(p_Val2_145_cast_fu_2788_p1) + $signed(p_Val2_19_cast_fu_1108_p1));

assign tmp48_cast_fu_3060_p1 = $signed(tmp47_fu_3054_p2);

assign tmp48_fu_3070_p2 = (p_Result_1_cast_fu_880_p1 + p_Result_3_cast_fu_920_p1);

assign tmp49_cast_fu_3656_p1 = tmp49_reg_3819;

assign tmp49_fu_3646_p2 = (tmp73_cast_fu_3642_p1 + tmp50_cast_fu_3578_p1);

assign tmp4_cast_fu_3372_p1 = $signed(tmp4_fu_3366_p2);

assign tmp4_fu_3366_p2 = ($signed(tmp7_cast_fu_3363_p1) + $signed(tmp5_cast_fu_3360_p1));

assign tmp50_cast_fu_3578_p1 = tmp50_fu_3572_p2;

assign tmp50_fu_3572_p2 = (tmp62_cast_fu_3568_p1 + tmp51_cast_fu_3552_p1);

assign tmp51_cast_fu_3552_p1 = tmp51_fu_3546_p2;

assign tmp51_fu_3546_p2 = (tmp57_cast_fu_3543_p1 + tmp52_cast_fu_3540_p1);

assign tmp52_cast_fu_3540_p1 = tmp52_reg_3759;

assign tmp52_fu_3102_p2 = (tmp55_cast_fu_3098_p1 + tmp53_cast_fu_3082_p1);

assign tmp53_cast_fu_3082_p1 = tmp53_fu_3076_p2;

assign tmp53_fu_3076_p2 = (tmp48_fu_3070_p2 + p_Result_12_cast_fu_1120_p1);

assign tmp54_fu_3086_p2 = (p_Result_7_cast_fu_1000_p1 + p_Result_9_cast_fu_1040_p1);

assign tmp55_cast_fu_3098_p1 = tmp55_fu_3092_p2;

assign tmp55_fu_3092_p2 = (tmp54_fu_3086_p2 + p_Result_5_cast_fu_960_p1);

assign tmp56_fu_3108_p2 = (p_Result_14_cast_fu_1160_p1 + p_Result_16_cast_fu_1200_p1);

assign tmp57_cast_fu_3543_p1 = tmp57_reg_3764;

assign tmp57_fu_3140_p2 = (tmp60_cast_fu_3136_p1 + tmp58_cast_fu_3120_p1);

assign tmp58_cast_fu_3120_p1 = tmp58_fu_3114_p2;

assign tmp58_fu_3114_p2 = (tmp56_fu_3108_p2 + p_Result_10_cast_fu_1080_p1);

assign tmp59_fu_3124_p2 = (p_Result_20_cast_fu_1280_p1 + p_Result_22_cast_fu_1320_p1);

assign tmp5_cast_fu_3360_p1 = $signed(tmp5_reg_3679);

assign tmp5_fu_2814_p2 = ($signed(tmp6_cast_fu_2810_p1) + $signed(p_Val2_1_cast_fu_868_p1));

assign tmp60_cast_fu_3136_p1 = tmp60_fu_3130_p2;

assign tmp60_fu_3130_p2 = (tmp59_fu_3124_p2 + p_Result_18_cast_fu_1240_p1);

assign tmp61_fu_3146_p2 = (p_Result_26_cast_fu_1400_p1 + p_Result_28_cast_fu_1440_p1);

assign tmp62_cast_fu_3568_p1 = tmp62_fu_3562_p2;

assign tmp62_fu_3562_p2 = (tmp68_cast_fu_3559_p1 + tmp63_cast_fu_3556_p1);

assign tmp63_cast_fu_3556_p1 = tmp63_reg_3769;

assign tmp63_fu_3178_p2 = (tmp66_cast_fu_3174_p1 + tmp64_cast_fu_3158_p1);

assign tmp64_cast_fu_3158_p1 = tmp64_fu_3152_p2;

assign tmp64_fu_3152_p2 = (tmp61_fu_3146_p2 + p_Result_24_cast_fu_1360_p1);

assign tmp65_fu_3162_p2 = (p_Result_32_cast_fu_1520_p1 + p_Result_34_cast_fu_1560_p1);

assign tmp66_cast_fu_3174_p1 = tmp66_fu_3168_p2;

assign tmp66_fu_3168_p2 = (tmp65_fu_3162_p2 + p_Result_30_cast_fu_1480_p1);

assign tmp67_fu_3184_p2 = (p_Result_38_cast_fu_1640_p1 + p_Result_40_cast_fu_1680_p1);

assign tmp68_cast_fu_3559_p1 = tmp68_reg_3774;

assign tmp68_fu_3216_p2 = (tmp71_cast_fu_3212_p1 + tmp69_cast_fu_3196_p1);

assign tmp69_cast_fu_3196_p1 = tmp69_fu_3190_p2;

assign tmp69_fu_3190_p2 = (tmp67_fu_3184_p2 + p_Result_36_cast_fu_1600_p1);

assign tmp6_cast_fu_2810_p1 = $signed(tmp6_fu_2804_p2);

assign tmp6_fu_2804_p2 = ($signed(p_Val2_4_cast_fu_908_p1) + $signed(p_Val2_7_cast_fu_948_p1));

assign tmp70_fu_3200_p2 = (p_Result_44_cast_fu_1760_p1 + p_Result_46_cast_fu_1800_p1);

assign tmp71_cast_fu_3212_p1 = tmp71_fu_3206_p2;

assign tmp71_fu_3206_p2 = (tmp70_fu_3200_p2 + p_Result_42_cast_fu_1720_p1);

assign tmp72_fu_3222_p2 = (p_Result_50_cast_fu_1880_p1 + p_Result_52_cast_fu_1920_p1);

assign tmp73_cast_fu_3642_p1 = tmp73_fu_3636_p2;

assign tmp73_fu_3636_p2 = (tmp85_cast_fu_3632_p1 + tmp74_cast_fu_3594_p1);

assign tmp74_cast_fu_3594_p1 = tmp74_fu_3588_p2;

assign tmp74_fu_3588_p2 = (tmp80_cast_fu_3585_p1 + tmp75_cast_fu_3582_p1);

assign tmp75_cast_fu_3582_p1 = tmp75_reg_3779;

assign tmp75_fu_3254_p2 = (tmp78_cast_fu_3250_p1 + tmp76_cast_fu_3234_p1);

assign tmp76_cast_fu_3234_p1 = tmp76_fu_3228_p2;

assign tmp76_fu_3228_p2 = (tmp72_fu_3222_p2 + p_Result_48_cast_fu_1840_p1);

assign tmp77_fu_3238_p2 = (p_Result_56_cast_fu_2000_p1 + p_Result_58_cast_fu_2040_p1);

assign tmp78_cast_fu_3250_p1 = tmp78_fu_3244_p2;

assign tmp78_fu_3244_p2 = (tmp77_fu_3238_p2 + p_Result_54_cast_fu_1960_p1);

assign tmp79_fu_3260_p2 = (p_Result_62_cast_fu_2120_p1 + p_Result_64_cast_fu_2160_p1);

assign tmp7_cast_fu_3363_p1 = $signed(tmp7_reg_3684);

assign tmp7_fu_2830_p2 = ($signed(tmp8_cast_fu_2826_p1) + $signed(p_Val2_10_cast_fu_988_p1));

assign tmp80_cast_fu_3585_p1 = tmp80_reg_3784;

assign tmp80_fu_3292_p2 = (tmp83_cast_fu_3288_p1 + tmp81_cast_fu_3272_p1);

assign tmp81_cast_fu_3272_p1 = tmp81_fu_3266_p2;

assign tmp81_fu_3266_p2 = (tmp79_fu_3260_p2 + p_Result_60_cast_fu_2080_p1);

assign tmp82_fu_3276_p2 = (p_Result_68_cast_fu_2240_p1 + p_Result_70_cast_fu_2280_p1);

assign tmp83_cast_fu_3288_p1 = tmp83_fu_3282_p2;

assign tmp83_fu_3282_p2 = (tmp82_fu_3276_p2 + p_Result_66_cast_fu_2200_p1);

assign tmp84_fu_3298_p2 = (p_Result_74_cast_fu_2360_p1 + p_Result_76_cast_fu_2400_p1);

assign tmp85_cast_fu_3632_p1 = tmp85_fu_3626_p2;

assign tmp85_fu_3626_p2 = (tmp91_cast_fu_3622_p1 + tmp86_cast_fu_3598_p1);

assign tmp86_cast_fu_3598_p1 = tmp86_reg_3789;

assign tmp86_fu_3330_p2 = (tmp89_cast_fu_3326_p1 + tmp87_cast_fu_3310_p1);

assign tmp87_cast_fu_3310_p1 = tmp87_fu_3304_p2;

assign tmp87_fu_3304_p2 = (tmp84_fu_3298_p2 + p_Result_72_cast_fu_2320_p1);

assign tmp88_fu_3314_p2 = (p_Result_80_cast_fu_2480_p1 + p_Result_82_cast_fu_2520_p1);

assign tmp89_cast_fu_3326_p1 = tmp89_fu_3320_p2;

assign tmp89_fu_3320_p2 = (tmp88_fu_3314_p2 + p_Result_78_cast_fu_2440_p1);

assign tmp8_cast_fu_2826_p1 = $signed(tmp8_fu_2820_p2);

assign tmp8_fu_2820_p2 = ($signed(p_Val2_13_cast_fu_1028_p1) + $signed(p_Val2_16_cast_fu_1068_p1));

assign tmp90_fu_3336_p2 = (p_Result_86_cast_fu_2600_p1 + p_Result_88_cast_fu_2640_p1);

assign tmp91_cast_fu_3622_p1 = tmp91_fu_3616_p2;

assign tmp91_fu_3616_p2 = (tmp94_fu_3610_p2 + tmp92_cast_fu_3601_p1);

assign tmp92_cast_fu_3601_p1 = tmp92_reg_3794;

assign tmp92_fu_3342_p2 = (tmp90_fu_3336_p2 + p_Result_84_cast_fu_2560_p1);

assign tmp93_fu_3348_p2 = (p_Result_90_cast_fu_2680_p1 + p_Result_92_cast_fu_2720_p1);

assign tmp94_fu_3610_p2 = (tmp96_cast_fu_3607_p1 + tmp95_cast_fu_3604_p1);

assign tmp95_cast_fu_3604_p1 = tmp93_reg_3799;

assign tmp95_fu_3354_p2 = (p_Result_94_cast_fu_2760_p1 + p_Result_96_cast_fu_2800_p1);

assign tmp96_cast_fu_3607_p1 = tmp95_reg_3804;

assign tmp9_cast_fu_3388_p1 = $signed(tmp9_fu_3382_p2);

assign tmp9_fu_3382_p2 = ($signed(tmp12_cast_fu_3379_p1) + $signed(tmp10_cast_fu_3376_p1));

assign tmp_10_fu_1258_p4 = {{p_Val2_10_fu_1252_p2[15:5]}};

assign tmp_11_fu_1298_p4 = {{p_Val2_11_fu_1292_p2[15:5]}};

assign tmp_12_fu_1338_p4 = {{p_Val2_12_fu_1332_p2[15:5]}};

assign tmp_13_fu_1378_p4 = {{p_Val2_13_fu_1372_p2[15:5]}};

assign tmp_14_fu_1418_p4 = {{p_Val2_14_fu_1412_p2[15:5]}};

assign tmp_15_fu_1458_p4 = {{p_Val2_15_fu_1452_p2[15:5]}};

assign tmp_16_fu_1498_p4 = {{p_Val2_16_fu_1492_p2[15:5]}};

assign tmp_17_fu_1538_p4 = {{p_Val2_17_fu_1532_p2[15:5]}};

assign tmp_18_fu_1578_p4 = {{p_Val2_18_fu_1572_p2[15:5]}};

assign tmp_19_fu_1618_p4 = {{p_Val2_19_fu_1612_p2[15:5]}};

assign tmp_1_fu_858_p4 = {{p_Val2_s_fu_852_p2[15:5]}};

assign tmp_20_fu_1658_p4 = {{p_Val2_20_fu_1652_p2[15:5]}};

assign tmp_21_fu_1698_p4 = {{p_Val2_21_fu_1692_p2[15:5]}};

assign tmp_22_fu_1738_p4 = {{p_Val2_22_fu_1732_p2[15:5]}};

assign tmp_23_fu_1778_p4 = {{p_Val2_23_fu_1772_p2[15:5]}};

assign tmp_24_fu_1818_p4 = {{p_Val2_24_fu_1812_p2[15:5]}};

assign tmp_25_fu_1858_p4 = {{p_Val2_25_fu_1852_p2[15:5]}};

assign tmp_26_fu_1898_p4 = {{p_Val2_26_fu_1892_p2[15:5]}};

assign tmp_27_fu_1938_p4 = {{p_Val2_27_fu_1932_p2[15:5]}};

assign tmp_28_fu_1978_p4 = {{p_Val2_28_fu_1972_p2[15:5]}};

assign tmp_29_fu_2018_p4 = {{p_Val2_29_fu_2012_p2[15:5]}};

assign tmp_2_fu_1058_p4 = {{p_Val2_5_fu_1052_p2[15:5]}};

assign tmp_30_fu_2058_p4 = {{p_Val2_30_fu_2052_p2[15:5]}};

assign tmp_31_fu_2098_p4 = {{p_Val2_31_fu_2092_p2[15:5]}};

assign tmp_32_fu_2138_p4 = {{p_Val2_32_fu_2132_p2[15:5]}};

assign tmp_33_fu_2178_p4 = {{p_Val2_33_fu_2172_p2[15:5]}};

assign tmp_34_fu_2218_p4 = {{p_Val2_34_fu_2212_p2[15:5]}};

assign tmp_35_fu_2258_p4 = {{p_Val2_35_fu_2252_p2[15:5]}};

assign tmp_36_fu_2298_p4 = {{p_Val2_36_fu_2292_p2[15:5]}};

assign tmp_37_fu_2338_p4 = {{p_Val2_37_fu_2332_p2[15:5]}};

assign tmp_38_fu_2378_p4 = {{p_Val2_38_fu_2372_p2[15:5]}};

assign tmp_39_fu_2418_p4 = {{p_Val2_39_fu_2412_p2[15:5]}};

assign tmp_3_fu_1098_p4 = {{p_Val2_6_fu_1092_p2[15:5]}};

assign tmp_40_fu_2458_p4 = {{p_Val2_40_fu_2452_p2[15:5]}};

assign tmp_41_fu_2498_p4 = {{p_Val2_41_fu_2492_p2[15:5]}};

assign tmp_42_fu_2538_p4 = {{p_Val2_42_fu_2532_p2[15:5]}};

assign tmp_43_fu_2578_p4 = {{p_Val2_43_fu_2572_p2[15:5]}};

assign tmp_44_fu_2618_p4 = {{p_Val2_44_fu_2612_p2[15:5]}};

assign tmp_45_fu_2658_p4 = {{p_Val2_45_fu_2652_p2[15:5]}};

assign tmp_46_fu_2698_p4 = {{p_Val2_46_fu_2692_p2[15:5]}};

assign tmp_47_fu_2738_p4 = {{p_Val2_47_fu_2732_p2[15:5]}};

assign tmp_48_fu_2778_p4 = {{p_Val2_48_fu_2772_p2[15:5]}};

assign tmp_49_fu_872_p3 = p_Val2_s_fu_852_p2[32'd4];

assign tmp_4_fu_898_p4 = {{p_Val2_1_fu_892_p2[15:5]}};

assign tmp_50_fu_912_p3 = p_Val2_1_fu_892_p2[32'd4];

assign tmp_51_fu_952_p3 = p_Val2_2_fu_932_p2[32'd4];

assign tmp_52_fu_992_p3 = p_Val2_3_fu_972_p2[32'd4];

assign tmp_53_fu_1032_p3 = p_Val2_4_fu_1012_p2[32'd4];

assign tmp_54_fu_1072_p3 = p_Val2_5_fu_1052_p2[32'd4];

assign tmp_55_fu_1112_p3 = p_Val2_6_fu_1092_p2[32'd4];

assign tmp_56_fu_1152_p3 = p_Val2_7_fu_1132_p2[32'd4];

assign tmp_57_fu_1192_p3 = p_Val2_8_fu_1172_p2[32'd4];

assign tmp_58_fu_1232_p3 = p_Val2_9_fu_1212_p2[32'd4];

assign tmp_59_fu_1272_p3 = p_Val2_10_fu_1252_p2[32'd4];

assign tmp_5_fu_1018_p4 = {{p_Val2_4_fu_1012_p2[15:5]}};

assign tmp_60_fu_1312_p3 = p_Val2_11_fu_1292_p2[32'd4];

assign tmp_61_fu_1352_p3 = p_Val2_12_fu_1332_p2[32'd4];

assign tmp_62_fu_1392_p3 = p_Val2_13_fu_1372_p2[32'd4];

assign tmp_63_fu_1432_p3 = p_Val2_14_fu_1412_p2[32'd4];

assign tmp_64_fu_1472_p3 = p_Val2_15_fu_1452_p2[32'd4];

assign tmp_65_fu_1512_p3 = p_Val2_16_fu_1492_p2[32'd4];

assign tmp_66_fu_1552_p3 = p_Val2_17_fu_1532_p2[32'd4];

assign tmp_67_fu_1592_p3 = p_Val2_18_fu_1572_p2[32'd4];

assign tmp_68_fu_1632_p3 = p_Val2_19_fu_1612_p2[32'd4];

assign tmp_69_fu_1672_p3 = p_Val2_20_fu_1652_p2[32'd4];

assign tmp_6_fu_1138_p4 = {{p_Val2_7_fu_1132_p2[15:5]}};

assign tmp_70_fu_1712_p3 = p_Val2_21_fu_1692_p2[32'd4];

assign tmp_71_fu_1752_p3 = p_Val2_22_fu_1732_p2[32'd4];

assign tmp_72_fu_1792_p3 = p_Val2_23_fu_1772_p2[32'd4];

assign tmp_73_fu_1832_p3 = p_Val2_24_fu_1812_p2[32'd4];

assign tmp_74_fu_1872_p3 = p_Val2_25_fu_1852_p2[32'd4];

assign tmp_75_fu_1912_p3 = p_Val2_26_fu_1892_p2[32'd4];

assign tmp_76_fu_1952_p3 = p_Val2_27_fu_1932_p2[32'd4];

assign tmp_77_fu_1992_p3 = p_Val2_28_fu_1972_p2[32'd4];

assign tmp_78_fu_2032_p3 = p_Val2_29_fu_2012_p2[32'd4];

assign tmp_79_fu_2072_p3 = p_Val2_30_fu_2052_p2[32'd4];

assign tmp_7_fu_938_p4 = {{p_Val2_2_fu_932_p2[15:5]}};

assign tmp_80_fu_2112_p3 = p_Val2_31_fu_2092_p2[32'd4];

assign tmp_81_fu_2152_p3 = p_Val2_32_fu_2132_p2[32'd4];

assign tmp_82_fu_2192_p3 = p_Val2_33_fu_2172_p2[32'd4];

assign tmp_83_fu_2232_p3 = p_Val2_34_fu_2212_p2[32'd4];

assign tmp_84_fu_2272_p3 = p_Val2_35_fu_2252_p2[32'd4];

assign tmp_85_fu_2312_p3 = p_Val2_36_fu_2292_p2[32'd4];

assign tmp_86_fu_2352_p3 = p_Val2_37_fu_2332_p2[32'd4];

assign tmp_87_fu_2392_p3 = p_Val2_38_fu_2372_p2[32'd4];

assign tmp_88_fu_2432_p3 = p_Val2_39_fu_2412_p2[32'd4];

assign tmp_89_fu_2472_p3 = p_Val2_40_fu_2452_p2[32'd4];

assign tmp_8_fu_1178_p4 = {{p_Val2_8_fu_1172_p2[15:5]}};

assign tmp_90_fu_2512_p3 = p_Val2_41_fu_2492_p2[32'd4];

assign tmp_91_fu_2552_p3 = p_Val2_42_fu_2532_p2[32'd4];

assign tmp_92_fu_2592_p3 = p_Val2_43_fu_2572_p2[32'd4];

assign tmp_93_fu_2632_p3 = p_Val2_44_fu_2612_p2[32'd4];

assign tmp_94_fu_2672_p3 = p_Val2_45_fu_2652_p2[32'd4];

assign tmp_95_fu_2712_p3 = p_Val2_46_fu_2692_p2[32'd4];

assign tmp_96_fu_2752_p3 = p_Val2_47_fu_2732_p2[32'd4];

assign tmp_97_fu_2792_p3 = p_Val2_48_fu_2772_p2[32'd4];

assign tmp_9_fu_1218_p4 = {{p_Val2_9_fu_1212_p2[15:5]}};

assign tmp_fu_2836_p2 = ($signed(p_Val2_25_cast_fu_1188_p1) + $signed(p_Val2_28_cast_fu_1228_p1));

assign tmp_s_fu_978_p4 = {{p_Val2_3_fu_972_p2[15:5]}};

endmodule //fp_sop
